### ISSUE TITLE
Update reviewer info

### ISSUE THREAD

**Issue by ledell** [ropensci/onboarding#100]
Hi @sckott,
Can you update my name & github repo URL in the `onboarding/README.md` doc?  I was going to change it and submit a PR, but I see that you are storing the reviewer data in an airtable that I can't edit in `onboarding/README.Rmd`.

From:
-   [Erin Ledell](https://github.com/NA)

To:
-   [Erin LeDell](https://github.com/ledell)

Thanks!

**Comment by sckott** [comment]
@ledell yes of course, thanks!

**Comment by sckott** [comment]
fixed
