### ISSUE TITLE
Add reviewer guidelines?

### ISSUE THREAD

**Issue by karthik** [ropensci/onboarding#11]
* Some general guidelines
* General advice (be kind, an order of magnitude kinder than CRAN when giving feedback etc?)

**Comment by sckott** [comment]
should those be in the wiki, adding to/replacing https://github.com/ropensci/onboarding/wiki/For-Reviewers

**Comment by sckott** [comment]
definitely +1 on being kind

**Comment by sckott** [comment]
@cboettig @jennybc @richfitz if you have any feedback on reviewer guidelines - see wiki

**Comment by karthik** [comment]
Just added a line to that effect. But more guidelines/feedback are welcome.

**Comment by karthik** [comment]
Closing for now, but go ahead and edit the wiki as needed.
