### ISSUE TITLE
virustotal: R client for Google's virustotal API 

### ISSUE THREAD

**Issue by soodoku** [ropensci/onboarding#111]
### Summary

-   What does this package do? (explain in 50 words or less):
Makes it easier to use VirusTotal, a Google service that analyzes files and URLs for viruses, worms, trojans etc., provides the category of the content hosted by a domain from a variety of prominent services, provides passive DNS information, among other things.

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: virustotal
Title: R Client for the VirusTotal API
Version: 0.2.0
Authors@R: person("Gaurav", "Sood", email = "gsood07@gmail.com", role = c("aut", "cre"))
Maintainer: Gaurav Sood <gsood07@gmail.com>
Description: Use VirusTotal, a Google service that analyzes files and URLs 
    for viruses, worms, trojans etc., provides category of the content hosted by a 
    domain from a variety of prominent services, provides passive DNS information,
    among other things. See <http://www.virustotal.com> for more information. 
URL: http://github.com/soodoku/virustotal
BugReports: http://github.com/soodoku/virustotal/issues
Depends:
    R (>= 3.3.0)
License: MIT + file LICENSE
LazyData: true
VignetteBuilder: knitr
Imports:
    httr,
    plyr
Suggests:
    knitr,
    rmarkdown,
    testthat
RoxygenNote: 6.0.1
```

-   URL for the package (the development repository, not a stylized html page):
https://github.com/soodoku/virustotal/

-   Who is the target audience?  
Security researchers, social scientists who want to study the kind of content that people consume.

-   Are there other R packages that accomplish the same thing? If so, what is different about yours?  
As far as I know, there aren't other such packages linking to the virustotal API

### Requirements

Confirm each of the following by checking the box.  This package:

- [x] does not violate the Terms of Service of any service it interacts with. 
- [x] has a CRAN and OSI accepted license.
- [x] contains a README with instructions for installing the development version. 
- [x] includes documentation with examples for all functions.
- [x] contains a vignette with examples of its essential functions and uses.
- [x] has a test suite.
- [x] has continuous integration with Travis CI and/or another service.

#### Publication options

- [x] Do you intend for this package to go on CRAN?  
- [ ] Do you wish to automatically submit to the [Journal of Open Source Software](http://joss.theoj.org/)? If so:
    - [ ] The package contains a [`paper.md`](http://joss.theoj.org/about#paper_structure) with a high-level description in the package root or in `inst/`.
    - [ ] The package is deposited in a long-term repository with the DOI: 
    - (*Do not submit your package separately to JOSS*)

### Detail

- [x] Does `R CMD check` (or `devtools::check()`) succeed?  Paste and describe any errors or warnings:

- [x] Does the package conform to [rOpenSci packaging guidelines](https://github.com/ropensci/packaging_guide)? Please describe any exceptions:

- If this is a resubmission following rejection, please explain the change in circumstances:

- If possible, please provide recommendations of reviewers - those with experience with similar packages and/or likely users of your package - and their GitHub user names:

**Comment by sckott** [comment]
hi @soodoku thanks for your submission! 

At the moment, we don't see it fitting in ropensci (see ropensci fit guidelines https://github.com/ropensci/onboarding/blob/master/policies.md#package-fit), but if you think it does we'd be happy to hear your argument.

**Comment by soodoku** [comment]
Thanks, @sckott. 

My sense is that the only case that can be made is around: "data retrieval (from APIs, data storage services, journals, and other remote servers). The data retrieved must have a scientific application and merely wrapping an API that serves data does not meet our criteria."

virustotal can provide, for instance, the category of the content hosted by a domain, which can be useful for people analyzing Internet consumption data. For instance, you could analyze from browsing records provided by ComScore for 100k panelists, whether lower income or less educated people visit potentially harmful (as in sites that will infect your computer) sites more often. 

But, I am happy to defer to you in these matters. There are lots of marginal research cases that can be made for lots of data. All of this is on a scale, and I am perfectly fine with having cut-offs.

**Comment by sckott** [comment]
hi - we discussed and think this is out of scope for ropensci. 

we really really do appreciate the submission though 😸
