### ISSUE TITLE
Fastrack for CRAN packages

### ISSUE THREAD

**Issue by karthik** [ropensci/onboarding#12]
For users submitting packages on CRAN, should we fastrack those (assuming the fit is good)? or still put it through all the checks and such?
I suppose it is likely that a package with no tests/CI will come to us (but be fine for CRAN).

**Comment by sckott** [comment]
Seems like we should still check all the things we want for ropensci (tests, good docs, etc. ) even if already on cran, or going to cran soon, cause as you said cran doesn't require much in terms of current best practice

**Comment by cboettig** [comment]
Agree with Scott; such reviews might be faster anyhow but maybe we don't
need an explicit policy of fast-tracking them?

**Comment by karthik** [comment]
> but maybe we don't
> need an explicit policy of fast-tracking them?

Right on . Makes sense.

**Comment by jennybc** [comment]
Agree. Very late, but agree :)
