### ISSUE TITLE
Automatic package checks

### ISSUE THREAD

**Issue by noamross** [ropensci/onboarding#125]
Now that **goodpractice** has an extension mechanism, here are some things we can write custom checks for:

- package has code of conduct
- exported functions are consistent in snake/camel naming convention 
- preferred packages are used
- the global environment is not directly manipulated
- package has CI and badges
- package uses appveyor is compiled code is included 
- common name conflicts are avoided
- If README has code, README.Rmd is used
- Package has a vignette 
- Package has top level documentation 

No time frame for this, but do add other things as you see them!

**Comment by maelle** [comment]
* CI doesn't skip tests

**Comment by maelle** [comment]
Reg. Windows another thing that's different is encoding (thinking of a bug I found for `EML` for instance), not sure how to define the case in which a package needs Appveyor because of possible encoding issues.

**Comment by sckott** [comment]
* could use available to check pkg name
* check if using roxygen style docs
* package has at least some tests
* check that all exported fxns have a `@examples` roxygen tag with at least 1 line of code (i.e., 1 example)
* might want to flag when people use `Depends` in `DESCRIPTION` to make sure it's really needed

**Comment by maelle** [comment]
Probably linked to the discussion in [this repo](https://github.com/lockedata/PackageReviewR/issues)

**Comment by mpadge** [comment]
Having just finished my review of @adamhsparks's excellent [`bomrang` package](https://github.com/ropensci/onboarding/issues/121), I encountered an interesting issue that could readily be incorporated into automatic tests. There are several ways to load a package, and this particular one passed all tests when loaded with `devtools::install_github()`, and with `install_packages()` from local tarball, yet it failed with `devtools::load_all()` from a cloned git repo. The reasons for failure were pretty clear (see [onboarding issue](https://github.com/ropensci/onboarding/issues/121) if you're really interested), but this flags an important aspect of package testing:

**Packages should be tested after loading in all possible different ways (three and counting)!**

**Comment by sckott** [comment]
thx @mpadge  for the interesting use case, not sure if we'll be able to do that, but can try
