### ISSUE TITLE
Test issue (please ignore)

### ISSUE THREAD

**Issue by karthik** [ropensci/onboarding#135]
### Summary

-   What does this package do? (explain in 50 words or less):

-   Paste the full DESCRIPTION file inside a code block below:

```

```

-   URL for the package (the development repository, not a stylized html page):

- Please indicate which category or categories from our [package fit policies](https://github.com/ropensci/onboarding/blob/master/policies.md#package-fit) this package falls under ***and why**(? (e.g., data retrieval, reproducibility. If you are unsure, we suggest you make a pre-submission inquiry.):

[e.g., "data extraction, because the package parses a scientific data file format"]

-   Who is the target audience?  

-   Are there other R packages that accomplish the same thing? If so, how does
yours differ or meet [our criteria for best-in-category](https://github.com/ropensci/onboarding/blob/master/policies.md#overlap)?

### Requirements

Confirm each of the following by checking the box.  This package:

- [ ] does not violate the Terms of Service of any service it interacts with. 
- [ ] has a CRAN and OSI accepted license.
- [ ] contains a README with instructions for installing the development version. 
- [ ] includes documentation with examples for all functions.
- [ ] contains a vignette with examples of its essential functions and uses.
- [ ] has a test suite.
- [ ] has continuous integration, including reporting of test coverage, using services such as Travis CI, Coeveralls and/or CodeCov.
- [ ] I agree to abide by [ROpenSci's Code of Conduct](https://github.com/ropensci/onboarding/blob/master/policies.md#code-of-conduct) during the review process and in maintaining my package should it be accepted.

#### Publication options

- [ ] Do you intend for this package to go on CRAN?  
- [ ] Do you wish to automatically submit to the [Journal of Open Source Software](http://joss.theoj.org/)? If so:
    - [ ] The package contains a [`paper.md`](http://joss.theoj.org/about#paper_structure) with a high-level description in the package root or in `inst/`.
    - [ ] The package is deposited in a long-term repository with the DOI: 
    - (*Do not submit your package separately to JOSS*)

### Detail

- [ ] Does `R CMD check` (or `devtools::check()`) succeed?  Paste and describe any errors or warnings:

- [ ] Does the package conform to [rOpenSci packaging guidelines](https://github.com/ropensci/onboarding/blob/master/packaging_guide.md)? Please describe any exceptions:

- If this is a resubmission following rejection, please explain the change in circumstances:

- If possible, please provide recommendations of reviewers - those with experience with similar packages and/or likely users of your package - and their GitHub user names:

**Comment by karthik** [comment]
Resolved all issues with badges! 🎉

**Comment by noamross** [comment]
Er, still no update on https://github.com/ropensci/roadoi, though the direct link works fine (https://ropensci.org/badges/115_status.svg).  Maybe previous ones need to be tickled somehow?  I note when I try to embed here I get yellow instead of green:

![](https://ropensci.org/badges/115_status.svg)

**Comment by maelle** [comment]
Same for https://github.com/ropensci/rtimicropem issue https://github.com/ropensci/onboarding/issues/126

**Comment by maelle** [comment]
Interestingly for `rtimicropem` while the GH README still has an orange badge, the [`pkgdown` website](http://ropensci.github.io/rtimicropem/) has a green badge.
