### ISSUE TITLE
lab.note

### ISSUE THREAD

**Issue by uribo** [ropensci/onboarding#14]
* 1. What does this package do? (explain in 50 words or less)  
Create laboratory note and report for helpful reproducible research.
* 2. Paste the full DESCRIPTION file inside a code block (bounded by ``` on either end).

```
Package: lab.note
Type: Package
Title: Create Laboratory Note and Presentation Using R Markdown
Version: 0.7.0
Date: 2015-05-21
Authors@R: person("Shinya", "Uryu", email = "suika1127@gmail.com", role = c("aut", "cre"))
Imports:
  knitr,
  rmarkdown
Suggests: 
  broom,
  dplyr, 
  ggplot2,
  ggvis,
  knitcitations,
  magrittr,
  shiny,
  tidyr,
  xtable
VignetteBuilder: knitr
URL: https://github.com/uribo/lab.note
BugReports: https://github.com/uribo/lab.note/issues
Description: Make it can reproducible R Markdown report and other format such as presentation and RPubs published files. Contains built-in useful package using R and LaTeX. These packages usages to see vignettes and wiki more information.
License: MIT + file LICENSE
```
* 3. URL for the package (the development repository, not a stylized html page)
    * https://github.com/uribo/lab.note
* 4. What data source(s) does it work with (if applicable)?
    * none.
* 5. Who is the target audience?
    * academic student and researcher.
* 6. Check the box next to each policy below, confirming that you agree. These are mandatory.
* [x] This package does not violate the Terms of Service of any service it interacts with.
* [x] The repository has continuous integration with Travis and/or another service
* [x] The package contains a vignette
* [x] The package contains a reasonably complete readme with devtools install instructions
* [ ] The package contains unit tests
* 7. Do you agree to follow the [rOpenSci packaging guidelines](https://github.com/ropensci/packaging_guide)? These aren't mandatory, but we strongly suggest you follow them. If you disagree with anything, please explain.
* [x] Are there any package dependencies not on CRAN?
* [x] Do you intend for this package to go on CRAN?
* [x] Does the package have a CRAN accepted license?
* [x] Did `devtools::check()` produce any errors or warnings? If so paste them below.
    * no
* 8. Please add explanations below for any exceptions to the above:
* 9. If this is a resubmission following rejection, please explain the change in cirucmstances.

**Comment by sckott** [comment]
hi @uribo thanks for the submission. It looks like you do use a CRAN accepted license (MIT) - please check that box. Also, answer the questions (if answer is No, then write that.) 

- Are there any package dependencies not on CRAN?
- Did devtools::check() produce any errors or warnings?

**Comment by sckott** [comment]
@cboettig assigned

**Comment by uribo** [comment]
Sorry, @sckott 

I'm fixed checkbox and answered for question. 

* Are there other R packages that accomplish the same thing? If so, what is different about yours?
  
similar packages (Rmd template packages)
*  mosaic ([CRAN](http://cran.r-project.org/web/packages/mosaic/index.html))
* rticles ([GitHub](https://github.com/rstudio/rticles)) 
* rmdTemplates ([GitHub](https://github.com/Pakillo/rmdTemplates))
* MarkdownMS ([GitHub](https://github.com/MarcoDVisser/MarkdownMS))

`lab.note` contains helpful and useful packages (i.e. knitr chunk option, custom font) using R reporting for **LaTeX beginner**. Also, default RMarkdown beamer templates are difficult to use while `lab.note` beamer template is already some initial configuration.

**Comment by sckott** [comment]
thanks for clarification @uribo

**Comment by sckott** [comment]
Hi @uribo - Sorry for the delay. 

We discussed your submission, and have decided that your submission is out of scope for rOpenSci.  We appreciate the work that has been done, and wish you the best!
