### ISSUE TITLE
Pre-submission Inquiry: rperseus

### ISSUE THREAD

**Issue by daranzolin** [ropensci/onboarding#144]
This is a pre-submission inquiry for `rperseus`, an R package that retrieves texts from the [Perseus Digital Library.](http://cts.perseids.org/) This package might add to the texts already available through packages like `rgutenberg`. The original Greek and Latin text is also available. 

* [Link to GitHub repo](https://github.com/daranzolin/rperseus)

If this package is considered a viable candidate, I'll develop it further so as to better align with rOpenSci's requirements.

Thanks!

**Comment by maelle** [comment]
@daranzolin thanks for your pre-submission! Do you have specific examples of scientific applications of these texts?

**Comment by maelle** [comment]
@daranzolin we editors all agree it's a good fit, looking forward to your submission! 

If you have any question regarding rOpenSci guidelines or something else during further package development don't hesitate to ask questions on [rOpenSci forum](https://discuss.ropensci.org/) or even via this thread if that's easier for you
