### ISSUE TITLE
Pre-submisstion Inquiry: cRegulome

### ISSUE THREAD

**Issue by MahShaaban** [ropensci/onboarding#146]
I'd like to make a pre-submission inquiry for the `cRegulome` R package. `cRegulome` provides programmatic access to transcription factors/mircoRNAs-gene expression correlation in cancer provided by [Cistrome Cancer](http://cistrome.org/CistromeCancer/) and [miRCancerdb](https://mahshaaban.shinyapps.io/miRCancerdb/) respectively. In addition, the package provides S3 classes and methods to store, manage and visualize the correlation data. 

The github repo:
[https://github.com/MahShaaban/cRegulome](https://github.com/MahShaaban/cRegulome)

I am looking forward to hearing whether I should proceed with to the submission and any comment or suggestion are appreciated.

**Comment by sckott** [comment]
Thanks for your pre-submission inquiry @MahShaaban 

We'll discuss this and get back to you soon.

**Comment by sckott** [comment]
We've discussed this and it is in scope. We encourage you to submit the package.

If you have any question regarding rOpenSci guidelines or something else during further package development don't hesitate to ask questions on [rOpenSci forum](https://discuss.ropensci.org/) or even via this thread if that's easier for you

**Comment by MahShaaban** [comment]
Thanks a lot @sckott. Will do.
