### ISSUE TITLE
Pre-submission Enquiry

### ISSUE THREAD

**Issue by steffilazerte** [ropensci/onboarding#150]
We (@boshek and I) are hoping to submit our package [`weathercan`](http://github.com/steffilazerte/weathercan) to rOpenSci for review in the near future, but acknowledge that another package [`rclimateca`](https://cran.r-project.org/package=rclimateca) is already available on CRAN (but not on rOpenSci).

Both packages concern the downloading of Environment and Climate Change Canada weather data into an easy format for use in R.

The largest difference between the two packages is that `weathercan` includes functions for interpolating weather data and directly integrating it into other data sources. Another difference is that `weathercan` actively seeks to apply *tidy* data principles in R and integrates well with the `tidyverse` including using tibbles and nested listcols. The `weathercan` package also includes a [website and tutorials/vignettes](http://steffilazerte.github.io/weathercan). We would also argue that `weathercan` is slightly more user-friendly.

Does this constitute a "Package Overlap" problem? Or should we still go ahead with the submission?

**Comment by sckott** [comment]
Thanks for your presub inquiry @steffilazerte 

We're discussing this and will get back to you soon

**Comment by sckott** [comment]
@steffilazerte we editors all agree it's a good fit, looking forward to your submission! 

If you have any question regarding rOpenSci guidelines or something else during further package development don't hesitate to ask questions on [rOpenSci forum](https://discuss.ropensci.org/) or even via this thread if that's easier for you
