### ISSUE TITLE
New submission:  FishLife

### ISSUE THREAD

**Issue by James-Thorson** [ropensci/onboarding#151]
### Summary

-   What does this package do? (explain in 50 words or less):
Reposits predicted life-history parameters (regarding mortality, growth, size) for more than 30,000 fishes scraped from FishBase using `rfishbase`.  Also provides code to update predictions, replicate results, and visualize predictions. 

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: FishLife
Type: Package
Title: Predict Life History Traits For Any Fish
Version: 1.0.2
Date: 2017-08-04
Authors@R: person("James","Thorson", email="James.Thorson@noaa.gov", role=c("aut","cre"))
Maintainer: James Thorson <James.Thorson@noaa.gov>
Description: Estimate life history traits from a multivariate 
    random-walk process on a taxonomic tree, and use results to 
    predicts traits for any marine fish scientific (Genus-species) name.
Imports:
    graphics,
    utils,
    stats,
    devtools,
    shape,
    rfishbase
Depends:
    R (>= 3.1.0),
Suggests:
    TMB,
    testthat
License: GPL-3
LazyData: yes
BuildVignettes: yes
RoxygenNote: 5.0.1
URL: http://github.com/James-Thorson/FishLife
BugReports: http://github.com/James-Thorson/Thorson/FishLife/issues
```

-   URL for the package (the development repository, not a stylized html page):
https://github.com/James-Thorson/FishLife/tree/master/R

- Please indicate which category or categories from our [package fit policies](https://github.com/ropensci/onboarding/blob/master/policies.md#package-fit) this package falls under ***and why**(? (e.g., data retrieval, reproducibility. If you are unsure, we suggest you make a pre-submission inquiry.):
Data retrieval, because the package distributes life-history predictions generated by a model that has already passed peer review at Ecological Applications (as discussed with Carl Boettiger by email, Aug. 14, 2017)

[e.g., "data extraction, because the package parses a scientific data file format"]

-   Who is the target audience?  
Fisheries biologists, fisheries managers, recreational and commercial fishers.

-   Are there other R packages that accomplish the same thing? If so, how does
yours differ or meet [our criteria for best-in-category](https://github.com/ropensci/onboarding/blob/master/policies.md#overlap)?

`rfishbase` distributes model estimates of life-history parameters that are reposited at FishBase.  `FishLife` generates a more reliable form of data based on output from `rfishbase`.  

### Requirements

Confirm each of the following by checking the box.  This package:

- [X] does not violate the Terms of Service of any service it interacts with. 
- [X] has a CRAN and OSI accepted license.
- [X] contains a README with instructions for installing the development version. 
- [x] includes documentation with examples for all functions.
- [] contains a vignette with examples of its essential functions and uses.
- [ ] has a test suite.
- [ ] has continuous integration, including reporting of test coverage, using services such as Travis CI, Coeveralls and/or CodeCov.
- [X] I agree to abide by [ROpenSci's Code of Conduct](https://github.com/ropensci/onboarding/blob/master/policies.md#code-of-conduct) during the review process and in maintaining my package should it be accepted.

#### Publication options

- [ ] Do you intend for this package to go on CRAN?  
- [ ] Do you wish to automatically submit to the [Journal of Open Source Software](http://joss.theoj.org/)? If so:
    - [ ] The package has an **obvious research application** according to [JOSS's definition](http://joss.theoj.org/about#submission_requirements).
    - [ ] The package contains a `paper.md` matching [JOSS's requirements](http://joss.theoj.org/about#paper_structure) with a high-level description in the package root or in `inst/`.
    - [X] The package is deposited in a long-term repository with the DOI: 
    - (*Do not submit your package separately to JOSS*)

### Detail

- [X] Does `R CMD check` (or `devtools::check()`) succeed?  Paste and describe any errors or warnings:

"
R CMD check results
0 errors | 2 warnings | 2 notes
checking dependencies in R code ... WARNING
'::' or ':::' import not declared from: 'TMBhelper'
'library' or 'require' call to 'TMB' in package code.
  Please use :: or requireNamespace() instead.
  See section 'Suggested packages' in the 'Writing R Extensions' manual.

checking Rd \usage sections ... WARNING
Undocumented arguments in documentation object 'Update_prediction'
  'Taxon' 'partial_match' 'verbose' 'ParentChild_gz' 'Cov_gjj'
  'Mean_gj' 'Version' 'TmbDir' 'RunDir'
"

- [X] Does the package conform to [rOpenSci packaging guidelines](https://github.com/ropensci/onboarding/blob/master/packaging_guide.md)? Please describe any exceptions:

However, I have not added Travis-CI, examples, or a vingette.  I have example code listed in the README, and I don't see any obvious example of what to add for continuous integration.  I am willing to discuss creating a vingette although it seems redundant with what's in the README.  I also use slightly different naming conventions for the package `FishLife` and functions e.g., `Plot_trait` (i.e., using capitol letters).  I am unwilling to change the package capitols (because the name is now published), but am willing to discuss changing naming conventions.

- If this is a resubmission following rejection, please explain the change in circumstances:

NA

- If possible, please provide recommendations of reviewers - those with experience with similar packages and/or likely users of your package - and their GitHub user names:

Carl Boetinger, cboettig
Anders Nielsen, fishfollower
Colin Millar, colinpmillar

**Comment by sckott** [comment]
thanks for your submission @James-Thorson - We're discussing this now and will get back to you soon

**Comment by sckott** [comment]
hi @James-Thorson 

We've discussed this and have decided that the package is out of scope for ropensci (see label attached now)

The main point is that we are not equipped in terms of editors and reviewers to review such a package that seems to be more on the "methods-y" side of things

Let me know if you have any questions.
