### ISSUE TITLE
Interest in submitting package

### ISSUE THREAD

**Issue by jrosen48** [ropensci/onboarding#158]
Hi rOpenSci team, I'm writing with a question about whether a package falls within the scope of rOpenSci.

The package is `konfound` and is to carry out sensitivity analysis for supporting causal inferences made from a) analyses already conducted (i.e., in other software) or analyses presented in published studies and b) models fit in R (e.g., linear models, generalized linear models, and [soon] mixed effects models).

Here is the description:

> R package to easily carry out sensitivity analysis as described in Frank, Maroulis, Duong, and Kelcey (2013) based on Rubin's (1974) causal model. Provides output for the replacement of cases and correlation based approaches in text, plot, or data frame form. Includes functionality to carry out sensitivity analysis for published studies as well as common models fit in R, as well as meta-analyses.

A link to the package, presently only on GitHub (and still being developed) is here: [https://github.com/jrosen48/konfound](https://github.com/jrosen48/konfound)

Thank you for your consideration.

**Comment by sckott** [comment]
Thanks for your pre-submission inquiry @jrosen48 

Editors will discuss and get back to you soon

**Comment by sckott** [comment]
Hi @jrosen48 

First, thanks for your submission!

We discussed and feel that it is not a good fit for rOpenSci. Although this is a neat package it appears to us as dealing primarily with statistics, which is not something covered within our current [Aims and Scope](https://github.com/ropensci/onboarding/blob/master/policies.md#aims-and-scope)

Do you have any questions/concerns about this decision?

**Comment by jrosen48** [comment]
Hi @sckott,

After reading again through the Aims and Scope, I understand the decision. At first, I thought it could possibly fit within the reproducibility category: I now think it is about reproducibility but in a different sense, less in terms of reproducible workflows / data analysis processes and more in terms of quantifying how likely an effect is to be reproduce in future studies.

Thank you for taking the time to consider this, I'll close the issue.

Josh

**Comment by sckott** [comment]
Thanks for considering us @jrosen48 😸
