### ISSUE TITLE
link to packaging_guide repo should be more visible

### ISSUE THREAD

**Issue by cboettig** [ropensci/onboarding#16]
@mbjones points out that we should probably make a more visible link to the ropensci packaging_guide, it's kinda buried in the contributing.md document.  Maybe it should also be linked from the README?

**Comment by karthik** [comment]
Excellent idea. Right now onboarding, policies, and packaging guide are not visibly linked anywhere. Making that more explicit here, and on the website would be great. :+1:

**Comment by sckott** [comment]
@noamross is this more visible in the new docs?
