### ISSUE TITLE
driftR Pre-Submission

### ISSUE THREAD

**Issue by chris-prener** [ropensci/onboarding#173]
This is a *pre-submission* inquiry based on a Twitter exchange with @maelle - we are interested to hear your thoughts on whether this package fits with ropensci!

### Summary

-   What does this package do? (explain in 50 words or less):
A tidy implementation of equations that correct for instrumental drift in continuous water quality monitoring data. There are many sources of water quality data, each of which are susceptible to errors/inaccuracies due to drift. This package allows the user to correct their data using one or two standard reference values in a uniform, reproducible way.

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: driftR
Type: Package
Title: Drift Correcting Water Quality Data
Version: 1.0.0
Authors@R: c(
    person("Andrew", "Shaughnessy", , "andrew.shaughnessy@slu.edu", c("aut", "cre")),
    person("Christopher", "Prener", , "chris.prener@slu.edu", c("aut")),
    person("Elizabeth", "Hasenmueller", , "elizabeth.hasenmueller@slu.edu", c("aut"))
    )
Description: A tidy implementation of equations that correct for instrumental drift in 
    continuous water quality monitoring data.  There are many sources of water quality data 
    including private (ex: YSI instruments) and open source (ex: USGS and NDBC), each of 
    which are susceptible to errors/inaccuracies due to drift. This package allows the 
    user to correct their data using one or two standard reference values in a uniform, 
    reproducible way. The equations implemented are from Hasenmueller (2011)
    <doi:10.7936/K7N014KS>.
License: GPL-3
URL: https://github.com/shaughnessyar/driftR
BugReports: https://github.com/shaughnessyar/driftR/issues
Encoding: UTF-8
LazyData: true
Imports: dplyr,
    ggplot2,
    readr,
    stringr,
    rlang,
    tibble,
    magrittr,
    glue
RoxygenNote: 6.0.1
Suggests: testthat, 
    knitr,
    rmarkdown,
    covr
VignetteBuilder: knitr
```

-   URL for the package (the development repository, not a stylized html page):
https://github.com/shaughnessyar/driftR

- Please indicate which category or categories from our [package fit policies](https://github.com/ropensci/onboarding/blob/master/policies.md#package-fit) this package falls under ***and why**(? (e.g., data retrieval, reproducibility. If you are unsure, we suggest you make a pre-submission inquiry.):
**Data Extraction**: The package includes a function for parsing output from a particular type of water quality monitoring instrument. We are planning to add additional functions to parse related instruments from different models / brands.

-   Who is the target audience and what are scientific applications of this package?  
The target audience are hydrology and geochemistry researchers who use continuous water quality monitoring instruments.

-   Are there other R packages that accomplish the same thing? If so, how does
yours differ or meet [our criteria for best-in-category](https://github.com/ropensci/onboarding/blob/master/policies.md#overlap)?
There are no R packages that accomplish the same thing. There are some very expensive proprietary packages for applying correction functions, and USGS has its own proprietary system that cannot be distributed publicly. Thus `driftR` fills an important niche for hydrologists and geoscientists.

-   If you made a pre-submission enquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.
This is a *pre-submission* inquiry based on a Twitter exchange with @maelle 

### Requirements

Confirm each of the following by checking the box.  This package:

- [x] does not violate the Terms of Service of any service it interacts with. 
- [x] has a CRAN and OSI accepted license.
- [x] contains a README with instructions for installing the development version. 
- [x] includes documentation with examples for all functions.
- [x] contains a vignette with examples of its essential functions and uses.
- [x] has a test suite.
- [x] has continuous integration, including reporting of test coverage, using services such as Travis CI, Coeveralls and/or CodeCov.
- [x] I agree to abide by [ROpenSci's Code of Conduct](https://github.com/ropensci/onboarding/blob/master/policies.md#code-of-conduct) during the review process and in maintaining my package should it be accepted.

#### Publication options

- [x] Do you intend for this package to go on CRAN?  - **Already on CRAN**
- [x] Do you wish to automatically submit to the [Journal of Open Source Software](http://joss.theoj.org/)? If so:
    - [x] The package has an **obvious research application** according to [JOSS's definition](http://joss.theoj.org/about#submission_requirements).
    - [ ] The package contains a `paper.md` matching [JOSS's requirements](http://joss.theoj.org/about#paper_structure) with a high-level description in the package root or in `inst/`. - **We will do this based on the outcome of the presubmission inquiry**
    - [x] The package is deposited in a long-term repository with the DOI: 
    - (*Do not submit your package separately to JOSS*)
- [ ] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:
	- [ ] The package is novel and will be of interest to the broad readership of the journal.
	- [ ] The manuscript describing the package is no longer than 3000 words.
	- [ ] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal.
	- (*Please do not submit your package separately to Methods in Ecology and Evolution*)

### Detail

- [x] Does `R CMD check` (or `devtools::check()`) succeed?  Paste and describe any errors or warnings:

- [x] Does the package conform to [rOpenSci packaging guidelines](https://github.com/ropensci/onboarding/blob/master/packaging_guide.md)? Please describe any exceptions:
Our package name does contain an upper-case letter, and our function names do combine snake case with camelCase - e.g. `dr_correctOne()`

- If this is a resubmission following rejection, please explain the change in circumstances:

- If possible, please provide recommendations of reviewers - those with experience with similar packages and/or likely users of your package - and their GitHub user names:

**Comment by maelle** [comment]
Link to Twitter exchange https://twitter.com/ma_salmon/status/941873240988897286

**Comment by karthik** [comment]
@chris-prener I'm just returning from break this week. Will update the thread shortly.

**Comment by chris-prener** [comment]
ok great @karthik - no worries!

**Comment by maelle** [comment]
@chris-prener thanks for considering a submission! Yes it'd fit in the data munging category but will be a more interesting submission once it handles several instruments which is your plan anyway. So submit it once it has a few more parsing functions for other instruments, so that the reviewed version might already be close to your "dream version". 😺

**Comment by chris-prener** [comment]
Thanks for the feedback @maelle - we'll look forward to submitting it later this year, then!

**Comment by maelle** [comment]
🎉😀

**Comment by maelle** [comment]
If you have any question in the meantime you can ping me here or ask in https://discuss.ropensci.org
