### ISSUE TITLE
rhmmer - presubmission

### ISSUE THREAD

**Issue by arendsee** [ropensci/onboarding#177]
### Summary

-   What does this package do? (explain in 50 words or less):

Parses output of HMMER into tidy data frames

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: rhmmer
Version: 0.1.0
Title: Utilities Parsing 'HMMER' Results 
Description:
    'HMMER' is a profile hidden Markov model tool used primarily for sequence
    analysis in bioinformatics (<http://hmmer.org/>). 'rhmmer' provides
    utilities for parsing the 'HMMER' output into tidy data frames.
Authors@R: person("Zebulun", "Arendsee", email="zbwrnz@gmail.com", role=c("aut","cre"))
URL: https://github.com/arendsee/rhmmer
BugReports: https://github.com/arendsee/rhmmer/issues
Depends:
    R (>= 3.4.0)
Imports:
    magrittr,
    readr,
    dplyr,
    tidyr,
    rlang
Suggests:
    testthat,
    covr,
    knitr,
    rmarkdown
LazyData: true
RoxygenNote: 6.0.1
License: GPL-3
VignetteBuilder: knitr
```

-   URL for the package (the development repository, not a stylized html page):

https://github.com/arendsee/rhmmer

- Please indicate which category or categories from our [package fit policies](https://github.com/ropensci/onboarding/blob/master/policies.md#package-fit) this package falls under ***and why**(? (e.g., data retrieval, reproducibility. If you are unsure, we suggest you make a pre-submission inquiry.):

data munging, because the package parses the idiosyncratic output of a tool into tidy data frames

-   Who is the target audience and what are scientific applications of this package?

Researchers in bioinformatics (especially genome annotation and sequence analysis) who want to analyze HMMER output in R.

-   Are there other R packages that accomplish the same thing? If so, how does
yours differ or meet [our criteria for best-in-category]

There are no other packages for working with the standalone version of HMMER. There are packages for submitting jobs to the online HMMER server (e.g. `Bio3D`), though these are necessarily limited to low-throughput analyses.

-   If you made a pre-submission enquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.

### Requirements

Confirm each of the following by checking the box.  This package:

- [x] does not violate the Terms of Service of any service it interacts with. 
- [x] has a CRAN and OSI accepted license.
- [x] contains a README with instructions for installing the development version. 
- [x] includes documentation with examples for all functions.
- [x] contains a vignette with examples of its essential functions and uses.
- [x] has a test suite.
- [x] has continuous integration, including reporting of test coverage, using services such as Travis CI, Coeveralls and/or CodeCov.
- [x] I agree to abide by [ROpenSci's Code of Conduct](https://github.com/ropensci/onboarding/blob/master/policies.md#code-of-conduct) during the review process and in maintaining my package should it be accepted.

#### Publication options

- [x] Do you intend for this package to go on CRAN?  

It already is on CRAN. But I can move the repository if accepted.

- [ ] Do you wish to automatically submit to the [Journal of Open Source Software](http://joss.theoj.org/)? If so:
    - [ ] The package has an **obvious research application** according to [JOSS's definition](http://joss.theoj.org/about#submission_requirements).
    - [ ] The package contains a `paper.md` matching [JOSS's requirements](http://joss.theoj.org/about#paper_structure) with a high-level description in the package root or in `inst/`.
    - [ ] The package is deposited in a long-term repository with the DOI: 
    - (*Do not submit your package separately to JOSS*)
- [ ] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:
	- [ ] The package is novel and will be of interest to the broad readership of the journal.
	- [ ] The manuscript describing the package is no longer than 3000 words.
	- [ ] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal.
	- (*Please do not submit your package separately to Methods in Ecology and Evolution*)

### Detail

- [x] Does `R CMD check` (or `devtools::check()`) succeed?  Paste and describe any errors or warnings:

- [x] Does the package conform to [rOpenSci packaging guidelines](https://github.com/ropensci/onboarding/blob/master/packaging_guide.md)? Please describe any exceptions:

- If this is a resubmission following rejection, please explain the change in circumstances:

- If possible, please provide recommendations of reviewers - those with experience with similar packages and/or likely users of your package - and their GitHub user names:

**Comment by arendsee** [comment]
I submit this as a presubmission because I am not certain whether it is substantial enough for entry into ropensci. It is a very minimal tool specific for interfacing with one program.

However, I think there are several useful directions in which it could evolve, so I wanted to share it with the community.

**Comment by karthik** [comment]
Thanks @arendsee 
We are looking into this now and will get back to you.

**Comment by karthik** [comment]
Hi @arendsee
The editors and I feel like this would be a good fit for a full submission. However, we are keen to learn if you think there is similar class of file types that this package could be expanded to handle?

**Comment by arendsee** [comment]
Off the cuff, I can think two other formats.

 1. The pfam format that is the default output of `hmmscan`. This would be a pretty heavy parse job. I would probably want to implement it in C++/Rcpp.

 2. The HMM profiles. Here I would want to do both reading and writing. Then we could develop the profiles in R and write them for use in HMMER.

There are other formats produced by HMMER tools besides `hmmscan`. I will check on them and get back to you with more info.

HMMER is an incredibly awesome tool with cool applications even outside of bioinformatics (it has been used to compare bird songs, for example). What I have written is pretty minimal, but I hope to find other programmers who are interested in building on `rhmmer` to better expose the functionality of HMMER to the R world.

I can commit to maintaining the current functions of `rhmmer`, but I am unlikely to personally add any new features. Rather I'd try to find collaborators, ideally someone actually associated with the HMMER project.

**Comment by arendsee** [comment]
Here are a few other formats:

 1. `hmmstat` profile statistics output

 2. `hmmlogo` output used to build logo plots from a profile

 3. `hmmalign` output, this is just Stockholm format, I suspect parsers for this format already exist. But we could add a wrapper.

 All of the outputs of HMMER also contain metadata, which I am currently not parsing out.

**Comment by arendsee** [comment]
@noamross Fair enough, thanks!
