### ISSUE TITLE
oneKP - submission

### ISSUE THREAD

**Issue by arendsee** [ropensci/onboarding#178]
### Summary

-   What does this package do? (explain in 50 words or less):

Access metadata and raw sequence data from the 1000 Plant Transcriptomes (1KP) initiative.

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: oneKP
Title: Retrieve Data from the 1000 Plants Initiative (1KP)
Version: 0.1.0
Authors@R: person("Zebulun", "Arendsee", email = "zbwrnz@gmail.com", role = c("aut", "cre"))
Description:
    The 1000 Plants Initiative (www.onekp.com) has sequenced the transcriptomes
    of over 1000 plant species. This package allows these sequences to be
    retrieved by species or recursively by clade. Scientific names and NCBI
    taxonomy IDs are both supported.
Depends: R (>= 3.4.0)
Imports:
    rvest,
    curl,
    readr,
    tidyr,
    magrittr,
    dplyr,
    xml2,
    methods,
    rlang,
    taxizedb
Remotes:
    ropensci/taxizedb
License: MIT + file LICENSE
Encoding: UTF-8
LazyData: true
RoxygenNote: 6.0.1
Suggests:
    testthat,
    covr,
    knitr,
    rmarkdown
VignetteBuilder: knitr
```

-   URL for the package (the development repository, not a stylized html page):

https://github.com/arendsee/oneKP

- Please indicate which category or categories from our [package fit policies](https://github.com/ropensci/onboarding/blob/master/policies.md#package-fit) this package falls under ***and why**(? (e.g., data retrieval, reproducibility. If you are unsure, we suggest you make a pre-submission inquiry.):

data retrieval - The core function of this program is to retrieve and filter data from 1KP

data munging - Scrapes data from the 1KP website and cleans it into tidy tables

-   Who is the target audience and what are scientific applications of this package?

Researchers in plant genomics and transcriptomics

-   Are there other R packages that accomplish the same thing? If so, how does
yours differ or meet [our criteria for best-in-category](https://github.com/ropensci/onboarding/blob/master/policies.md#overlap)?

No

-   If you made a pre-submission enquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.

### Requirements

Confirm each of the following by checking the box.  This package:

- [x] does not violate the Terms of Service of any service it interacts with. 
- [x] has a CRAN and OSI accepted license.
- [x] contains a README with instructions for installing the development version. 
- [x] includes documentation with examples for all functions.
- [x] contains a vignette with examples of its essential functions and uses.
- [x] has a test suite.
- [x] has continuous integration, including reporting of test coverage, using services such as Travis CI, Coeveralls and/or CodeCov.
- [x] I agree to abide by [ROpenSci's Code of Conduct](https://github.com/ropensci/onboarding/blob/master/policies.md#code-of-conduct) during the review process and in maintaining my package should it be accepted.

#### Publication options

- [x] Do you intend for this package to go on CRAN? 
- [ ] Do you wish to automatically submit to the [Journal of Open Source Software](http://joss.theoj.org/)? If so:
    - [ ] The package has an **obvious research application** according to [JOSS's definition](http://joss.theoj.org/about#submission_requirements).
    - [ ] The package contains a `paper.md` matching [JOSS's requirements](http://joss.theoj.org/about#paper_structure) with a high-level description in the package root or in `inst/`.
    - [ ] The package is deposited in a long-term repository with the DOI: 
    - (*Do not submit your package separately to JOSS*)
- [ ] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:
	- [ ] The package is novel and will be of interest to the broad readership of the journal.
	- [ ] The manuscript describing the package is no longer than 3000 words.
	- [ ] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal.
	- (*Please do not submit your package separately to Methods in Ecology and Evolution*)

### Detail

- [x] Does `R CMD check` (or `devtools::check()`) succeed?  Paste and describe any errors or warnings:

- [x] Does the package conform to [rOpenSci packaging guidelines](https://github.com/ropensci/onboarding/blob/master/packaging_guide.md)? Please describe any exceptions:

`oneKP` is dependent on the development version of the `taxizedb` program, which CRAN would not like.

- If this is a resubmission following rejection, please explain the change in circumstances:

- If possible, please provide recommendations of reviewers - those with experience with similar packages and/or likely users of your package - and their GitHub user names:

**Comment by karthik** [comment]
👋 @arendsee
We are almost caught up from the backlog of submissions over the break. A quick question. Do you have any potential users you could suggest as reviewers? No worries if you don't have any, but these are generally helpful to the editor (once assigned).

**Comment by arendsee** [comment]
The potential users that I know of are all associated with my lab and know me personally. I'm not sure if this represents a conflict of interest? If not, I can recommend two people who have used my tools before and are good at catching bugs and usability shortcomings.

**Comment by karthik** [comment]
Unfortunately yes, folks in your lab would present a COI.

**Comment by arendsee** [comment]
Yeah, I figured they would.

In that case, possibly the author of `biomartr`, Hajk-Georg Drost (HajkD).

**Comment by sckott** [comment]
### Editor checks:

- [x] **Fit**: The package meets criteria for [fit](policies.md#fit) and [overlap](policies.md#fit)
- [x] **Automated tests:** Package has a testing suite and is tested via Travis-CI or another CI service.
- [x] **License:** The package has a CRAN or OSI accepted license
- [x] **Repository:** The repository link resolves correctly
- [ ] **Archive** (JOSS only, may be post-review): The repository DOI resolves correctly
- [ ] **Version** (JOSS only, may be post-review): Does the release version given match the GitHub release (v1.0.0)?

---

#### Editor comments

Thanks for your submission @arendsee  !! 

- You can put a ropensci review badge in your README

`[![](https://badges.ropensci.org/178_status.svg)](https://github.com/ropensci/onboarding/issues/178)`

- Goodpractice output for you and reviewers to consider.

```r
It is good practice to

  ✖ write unit tests for all functions, and all package code
    in general. 91% of code lines are covered by test cases.

    R/generics.R:7:NA
    R/generics.R:8:NA
    R/generics.R:9:NA
    R/generics.R:10:NA
    R/generics.R:11:NA
    ... and 4 more lines

  ✖ add a "URL" field to DESCRIPTION. It helps users find
    information about your package online. If your package does not
    have a homepage, add an URL to GitHub, or the CRAN package package
    page.
  ✖ add a "BugReports" field to DESCRIPTION, and point it to
    a bug tracker. Many online code hosting services provide bug
    trackers for free, https://github.com, https://gitlab.com, etc.
  ✖ avoid long code lines, it is bad for readability. Also,
    many people prefer editor windows that are about 80 characters
    wide. Try make your lines shorter than 80 characters

    tests/testthat/test-all.R:11:1

  ✖ fix this R CMD check NOTE: Namespaces in Imports field
    not imported from: ‘readr’ ‘tidyr’ All declared Imports should be
    used.
```

Seeking reviewers now 🕐 

---

Reviewers:  xx xx
Due date: xxxx

**Comment by arendsee** [comment]
Thanks @sckott !

I'll address all the issues shortly.

**Comment by sckott** [comment]
You don't have to now - can also wait for reviews to come in firts

**Comment by sckott** [comment]
Reviewers assigned. 

Reviewers:  @jminnier @zachary-foster
Due date: 2018-02-13

**Comment by sckott** [comment]
@jminnier @zachary-foster just a reminder that your reviews are due in about a week

**Comment by zachary-foster** [comment]
## Zach's review of oneKP

@arendsee @sckott

*Please check off boxes as applicable, and elaborate in comments below.  Your review is not limited to these topics, as described in the reviewer guide*

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (If you are unsure whether you are in conflict, please speak to your editor _before_ starting your review).

#### Documentation

The package includes all the following forms of documentation:

- [ ] **A statement of need** clearly stating problems the software is designed to solve and its target audience in README
- [x] **Installation instructions:** for the development version of package and any non-standard dependencies in README
- [x] **Vignette(s)** demonstrating major functionality that runs successfully locally
- [x] **Function Documentation:** for all exported functions in R help
- [x] **Examples** for all exported functions in R Help that run successfully locally
- [ ] **Community guidelines** including contribution guidelines in the README or CONTRIBUTING, and DESCRIPTION with `URL`, `BugReports` and `Maintainer` (which may be autogenerated via `Authors@R`).

>##### For packages co-submitting to JOSS
>
>- [ ] The package has an **obvious research application** according to [JOSS's definition](http://joss.theoj.org/about#submission_requirements)
>
>The package contains a `paper.md` matching [JOSS's requirements](http://joss.theoj.org/about#paper_structure) with:
>
>- [ ] **A short summary** describing the high-level functionality of the software
>- [ ] **Authors:**  A list of authors with their affiliations
>- [ ] **A statement of need** clearly stating problems the software is designed to solve and its target audience.
>- [ ] **References:** with DOIs for all those that have one (e.g. papers, datasets, software).

#### Functionality

- [x] **Installation:** Installation succeeds as documented.
- [x] **Functionality:** Any functional claims of the software been confirmed.
- [x] **Performance:** Any performance claims of the software been confirmed.
- [x] **Automated tests:** Unit tests cover essential functions of the package
   and a reasonable range of inputs and conditions. All tests pass on the local machine.
- [ ] **Packaging guidelines**: The package conforms to the rOpenSci packaging guidelines

#### Final approval (post-review)

- [ ] **The author has responded to my review and made changes to my satisfaction. I recommend approving this package.**

Estimated hours spent reviewing: 

4


### Summary of review

This is a useful and straight-forward package that accomplishes a well-defined goal: to download all or a subset of protein/nucleotide sequence files from the 1KP website. Using this package seems much better then downloading the data from the 1KP website manually, which is not set up well for bulk downloads from what I have seen. There are some issues that should be addressed, but a lot of what I point out below is a matter of taste. Assuming some of the more important issues I describe below are addressed, I recommend that this package be accepted into rOpenSci.

### Review Comments

I will start with responses to questions posed in the [Reviewer's guide](https://github.com/ropensci/onboarding/blob/master/reviewing_guide.md#ropensci-package-reviewing-guide).


> Does the code comply with general principles in the Mozilla reviewing guide?

Yes

> Does the package comply with the ROpenSci packaging guide?

Mostly, but I say where I found differences below.

> Are there improvements that could be made to the code style?

Nothing too important.
According the Hadly's style guide, you should add spaces around `=`: 

```
    uncache = .cache_by_extension(old_ext='.faa.tar.bz2', new_ext='.faa')
```

 to
 
```
    uncache = .cache_by_extension(old_ext = '.faa.tar.bz2', new_ext = '.faa')
```

Its a minor point though.

> Is there code duplication in the package that should be reduced?

Nope

> Are there user interface improvements that could be made?

* The download functions should have an option for where to save the files. In my opinion, the default for the download functions should be a temporary folder, generated with `tempdir()` or `tempfile()`. Typically, I hear its best to avoid writing to disk unless the user specifically says where. Also you would not then need the `unlink('OneKP', recursive=TRUE)` at the end of the test. Deleting folders in code makes me nervous, but I am not sure if that is a rational fear or not.

* You can import the magrittr `%>%` pipe into your package so users don't have to `library(magrittr)`.

* When I run `retrieve_oneKP` I see two loading bars and they make me curious about what is going on. A description above each bar would be nice.

> Are there performance improvements that could be made?

Not that I saw.

> Is the documentation (installation instructions/vignettes/examples/demos) clear and sufficient?

Yes.

### Comments on unchecked boxes

**A statement of need**

Target audience is not explicitly stated, but it seems pretty clear it is anyone wanting to use data from 1KP in R, probably researchers. In his submission @arendsee says "Researchers in plant genomics and transcriptomics". It would be nice to add to the README, but in a way that doesn't imply that it is less useful/understandable to non-researchers. 

**Community guidelines**

Does not have contribution guidelines or a CONTRIBUTING file.

**Packaging guidelines**

* The guide states: "We strongly recommend short, descriptive names in lower case", so perhaps change the name to `onekp`?
* Package name not at top of readme. See https://github.com/ropensci/onboarding/blob/master/packaging_guide.md#-readme.
* No code of conduct. See https://github.com/ropensci/onboarding/blob/master/packaging_guide.md#-code-of-conduct
* Need `NEWS`/`NEWS.md` file in root folder. See https://github.com/ropensci/onboarding/blob/master/packaging_guide.md#-news

### Other comments

1. It might be a good idea to add the R devel build on Travis. I think CRAN will want that anyway.
1. Once your package is on CRAN, instructions for installation from CRAN and difference between the two installation type for new users would be nice as well for beginners.
1.  The `?oneKP` package man page could use a bit more description. Perhaps a link to the 1KP project website and the GitHub repo (where to report bugs and ask questions).
1. I don't think `print.OneKP` needs to be exported.
1. `retrieve_oneKP` could use some more description. Users might wonder: What kind of data am I retrieving? How is this different than the download functions?
1. Some of the examples that use the internet should probably be in `\dontrun{}` so as to avoid CRAN errors?
1. The "Accessing the OneKP metadata" section of the intro could use some for descriptions of what exactly is going on during that step.

**Comment by arendsee** [comment]
@zachary-foster Thanks for the review! Very good points across the board, I'll make all the suggested changes. Well, I don't like spaces around the equal signs in a function's argument list, but if that's what Hadley says ...

I should be able to commit the changes within a few days.

Thanks!

**Comment by arendsee** [comment]
I've changed the repo's name to `onekp`. I'll update the actual package name later. Anyway, this breaks the link to the repo, so here is the new url: [onekp](https://github.com/arendsee/onekp).

**Comment by sckott** [comment]
thanks for your review @zachary-foster !

**Comment by sckott** [comment]
@jminnier reminder that your review is due tomorrow

**Comment by jminnier** [comment]
thanks @sckott, hope to have it up tonight but definitely by sometime tomorrow!

**Comment by jminnier** [comment]
Sorry for pushing this to the last minute! I hope to not be so slow next time =)

## Package Review

*Please check off boxes as applicable, and elaborate in comments below.  Your review is not limited to these topics, as described in the reviewer guide*

- [X] As the reviewer I confirm that there are no conflicts of interest for me to review this work (If you are unsure whether you are in conflict, please speak to your editor _before_ starting your review).

#### Documentation

The package includes all the following forms of documentation:

- [X] **A statement of need** clearly stating problems the software is designed to solve and its target audience in README
- [X] **Installation instructions:** for the development version of package and any non-standard dependencies in README
- [X] **Vignette(s)** demonstrating major functionality that runs successfully locally
- [X] **Function Documentation:** for all exported functions in R help
- [X] **Examples** for all exported functions in R Help that run successfully locally
- [ ] **Community guidelines** including contribution guidelines in the README or CONTRIBUTING, and DESCRIPTION with `URL`, `BugReports` and `Maintainer` (which may be autogenerated via `Authors@R`).


#### Functionality

- [X] **Installation:** Installation succeeds as documented.
- [X] **Functionality:** Any functional claims of the software been confirmed.
- [X] **Performance:** Any performance claims of the software been confirmed.
- [X] **Automated tests:** Unit tests cover essential functions of the package
   and a reasonable range of inputs and conditions. All tests pass on the local machine.
- [ ] **Packaging guidelines**: The package conforms to the rOpenSci packaging guidelines

#### Final approval (post-review)

- [ ] **The author has responded to my review and made changes to my satisfaction. I recommend approving this package.**

Estimated hours spent reviewing: 4 (Including time spent reading example reviews, I'm new to this!)

---

### Review Comments

This package provides an interface to download sequencing data from the 1KP project. There are just a few functions, mainly to retreive the full data set, filter by various types of data queries, and then download the sequencing data based on the full data or on a filter. Overall the package works as intended and it is very useful to the community. I would recommend the package be accepted. My comments are all minor.

**Documentation:**

- I like the print properties of the `OneKP` object! There is no example in the `print.OneKP` function help page, but I don't think that is necessary? I'm not sure if that is typical.
- In the vignette and in the example for `filter_by*`, it would be helpful to show how to list the codes/species that you can filter on. I realize it is accessed in `onekp@table$code` but it took me a second to realize that.
- In the `?download` documentation, you say "These functions will return all files in the OneKP object of the given type (e.g. protein FASTA files for get_peptides)." Since there are only two options, peptides and nucleotides, can you say the file type for `get_nucleotides`? (i.e. what is an .fna file?)
- The `?oneKP` description is short, would be nice to have 1KP link here. [overlaps with @zachary-foster review]
- There isn't a separate vignette but the readme serves as one.

**Regarding packaging guidelines:**

- strongly recommend package name in lower case [overlaps with @zachary-foster review]
- Nice description in the `README`.
- I don't see a `NEWS` file? [overlaps with @zachary-foster review]
- 98% of code is covered by tests
- Contributing guidelines are mostly fulfilled but it would be nice to have a `contributing.md` file to explain how to contribute to the package. [overlaps with @zachary-foster review]

**Functions:**

- For the `download` functions, it would be useful to include an option set the location of files. It also might be helpful to have an option to return the full path to files as opposed to relative paths.

This code returns an error, which is good, but it would be useful to return a more clear error. Filtering on a non-existant species results in a 0 "length" oneKP object (ok), but then the `download_*` functions return a curl error due to a misspecified url.

```
tmp <- filter_by_species(onekp,"foobar") # returns object with 0 0
tmp
str(tmp@table)

download_nucleotides(tmp)
> Error in curl::curl_download(url = url, destfile = path, quiet = TRUE) : Argument 'url' must be string.
```

**Comment by sckott** [comment]
thanks so so much @jminnier for your review!  

> (Including time spent reading example reviews, I'm new to this!)

let us know if there's any way we can make it easier to get oriented (can ping me directly or any of our other places)

**Comment by arendsee** [comment]
Thanks @jminnier! I agree with all your points and will get an update out as soon possible.

**Comment by jminnier** [comment]
thanks for making a great package @arendsee! and @sckott the onboarding materials and review sheet and example reviews and ropensci blog posts were all amazing and extremely helpful as a newbee!

**Comment by arendsee** [comment]
@zachary-foster 

> When I run retrieve_oneKP I see two loading bars and they make me curious about what is going on. A description above each bar would be nice.

I think the bars you are seeing are from `taxizedb` (if so, you should only see them the first time you run `retrieve_oneKP`). Though adding bars there might be good.

In this function, I am downloading a database onto the users computer through `taxizedb`. I use this database to map species names to NCBI taxon IDs. If the user doesn't want this, they can set the `add_taxids` flag to `FALSE`. I could set the default to `FALSE`, but the IDs are required later if you want to filter by clade.

Anyway, is it OK if I don't fix this problem for now?

**Comment by arendsee** [comment]
@zachary-foster @jminnier 

Thanks for the great reviews! You comments were all really helpful.

I believe I have fixed everything now. All the changes are listed in the `NEWS.md` file.

@jminnier Nice catch of the corner case for downloading empty tables. The `download_*` functions return character vectors of downloaded filenames. So I think the right way to handle an empty input (e.g. where your filter left no transcriptomes in the dataset) is to return an empty character vector. I've also added some testing of other corner cases in the `filter_by_*` function (see `NEWS.md`).

**Comment by zachary-foster** [comment]
> Thanks for the great reviews! You comments were all really helpful.

@arendsee, thanks! Glad to hear it! Everything looks good to me. 

@sckott, my suggestions have been addressed, so `onekp` is ready as far as I am concerned.

**Comment by sckott** [comment]
@jminnier are you satisfied with the changes/responses?  also, you didn't check the box for `Packaging guidelines: The package conforms to the rOpenSci packaging guidelines` - was there something you saw that didn't fit out guidelines?

**Comment by jminnier** [comment]
Thanks, @arendsee, it all looks great to me! @sckott I agree with @zachary-foster, `onekp` looks ready for the world. I checked that box now, I think I left it because of the news and contributions bits but that all looks settled now anyway.

**Comment by sckott** [comment]
thanks @jminnier 

@arendsee  i'll take a quick look myself at the newest version

**Comment by sckott** [comment]
Some observations on the current version on master:

* i'm not super familiar with S4. you `importFrom methods new`, but not `setClass` or `representation` or `setMethod`, etc. What's best practice for pkgs that use S4?
* not crucial, but splitting up tests into files for each function (or whatever makes sense) might be useful, e.g., contributors would know more easily where to add a test
* notice you have remotes for `ropensci/taxizedb` in DESCRIPTION - i assume you need a minimum ver of that? should we prioritize getting a new ver of taxizedb to cran soon?

**Comment by arendsee** [comment]
@sckott 

 * I tend to use `importFrom` only when `check` screams at me, but currently it seems happy :)

 * I can split the tests, if you prefer. I put them all together because they share a common `OneKP` object, which takes some time to generate. `retrieve_onekp()` takes about 20 seconds to run, which is little enough that I didn't bother implementing special handling to cache the value, but long enough to be really annoying when testing.

 * Right, I'll add a minimum `taxizedb` version. And it would be great to get the current taxizedb stuff into cran -- I have more than one package that depends on it now. It will take a little work, especially updating the NEWS with all the NCBI database stuff. Also I've run into one or two other functions I want to add.

**Comment by sckott** [comment]
- okay
- makes sense, though maybe check on `tests/testthat/helper-.R` files https://github.com/ropensci/rrlite/tree/master/tests/testthat in which maybe you can run that download, and then the object may be available to any file, don't quote me on it
- ✔️ will help try to get `taxizedb` to cran sooner than later. 

> Also I've run into one or two other functions I want to add.

cool, looking forward to it

**Comment by arendsee** [comment]
@sckott I think I've addressed the test issues.

I added the output of `retrieve_onekp()`, the metadata table from the 1KP website, to the package data. So that it can now be accessed with `data(onekp)`. The data on the 1KP website is not guaranteed to be stable, so I added a test that compares the saved data to the online data (and set it to be skipped on CRAN or Travis).

I split the tests into small files (`test-retrieve.R`, `test-download.R`, and `test-filter.R`). All the tests use the package data, except for one test in `test-retrieve`.

I've also made the function examples use the package data (except for the `retrieve_onekp` function itself).

**Comment by arendsee** [comment]
@sckott Added minimum version for `taxizedb`

**Comment by sckott** [comment]
Approved!  Thanks again for your submission @arendsee 

* Please transfer the package  to `ropensci`- I've invited you to a team within our ropensci organization. After you accept you should be able to move it. You'll be made admin once you do.
* Make sure to 
    * add rOpenSci footer to README
`[![ropensci_footer](https://ropensci.org/public_images/ropensci_footer.png)](https://ropensci.org)`
    * Change any needed links, such those for CI badges
    * Travis CI should update to the new location automatically - you may have to update other CI systems manually
* Please do add a `.github` dir and the 3 files inside of it, see https://github.com/ropensci/dotgithubfiles/
* We're starting to roll out software metadata files to all ropensci pkgs via the Codemeta initiative, see  https://github.com/ropensci/codemetar/#codemetar  for how to include it in your pkg, after installing the pkg - should be easy as running `codemetar::write_codemeta()` in the root of your pkg

---

* Are you interested in doing a blog post for our blog https://ropensci.org/blog/ ?  either a short-form intro to it (https://ropensci.org/technotes/) or long-form post with more narrative about its development (https://ropensci.org/blog/). If so, we'll have our community manager @stefaniebutland get in touch with you on that

**Comment by arendsee** [comment]
Great! Thanks @sckott @karthik @zachary-foster  and @jminnier !

@sckott I'll move everything over and make the updates in a bit. I could do a blog post; I'm inclined towards the technotes, since this is a pretty small repo.

@zachary-foster @jminnier Thanks for the reviews, is it OK if I add you as reviewers to the DESCRIPTION?

**Comment by zachary-foster** [comment]
@arendsee No problem! 

>OK if I add you as reviewers to the DESCRIPTION?

Sure, thanks!

**Comment by jminnier** [comment]
@arendsee sounds great, thanks!

**Comment by arendsee** [comment]
@sckott @zachary-foster @jminnier OK! Everything is transferred and set up on rOpenSci! Thanks again!

https://github.com/ropensci/onekp

**Comment by stefaniebutland** [comment]
Hi @arendsee. Great to hear you're interested in contributing a [technote](https://ropensci.org/technotes/) (or full post). 

Here are some editorial and technical instructions for drafting and submitting a blog post via pull request to our site: https://github.com/ropensci/roweb2#contributing-a-blog-post. 

If it's a technote, the differences are:
- Create a new file in /content/technotes/YEAR-MONTH-DAY-short-slug.md 
- in YAML set `categories: technotes`

Blogs are published ~weekly and technotes can be published any time, after we have reviewed the pull request. 

Happy to answer any questions

**Comment by arendsee** [comment]
Hi @stefaniebutland, thanks for the info!

I've chalked "write technote" onto my TODO list. I'm a bit back-logged, so it might be awhile before I get to it.
