### ISSUE TITLE
pre-submission inquiry: new package

### ISSUE THREAD

**Issue by rvalavi** [ropensci/onboarding#180]
Hi, 
I want to submit my package to rOpenSci for the submission as a requirement of Methods in Ecology and Evolution journal. I wonder if I need to create a GitHub repository for an R package prior to the submission.

Kind regards,
Roozbeh

**Comment by karthik** [comment]
Hi Roozbeh,
Yes you'll need to create a git based repository for your project prior to submitting to our system. Once you've created a repository, fill out our submission template. More information on the submission steps are here: https://github.com/ropensci/onboarding#how-to-submit-your-package-for-review

**Comment by rvalavi** [comment]
Hi Karthik,
Thanks for the quick reply.
Regards,
Roozbeh
