### ISSUE TITLE
blockCV package

### ISSUE THREAD

**Issue by rvalavi** [ropensci/onboarding#182]
### Summary

-   What does this package do? (explain in 50 words or less):

The package facilitates spatial cross-validation procedure. It creates spatially or environmentally separated training and testing folds for cross-validation to provide a robust error estimation in spatially structured environments. It also investigates the spatial autocorrelation in raster covariates to find an initial realistic distance band to separate training and testing datasets spatially.

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: blockCV
Type: Package
Title: Spatial and environmental blocking for k-fold cross-validation
Version: 0.1.0
Date: 2018-01-04
Authors@R: c(person("Roozbeh", "Valavi", role = c("aut", "cre"),
                    email = "valavi.r@gmail.com"),
             person("Gurutzeta", "Guillera-Arroita", role = "aut",
                    email = "gurutzeta.guillera@unimelb.edu.au"),
             person("José", "Lahoz-Monfort", role = "aut",
                    email = "jose.lahoz@unimelb.edu.au"),
             person("Jane", "Elith", role = "aut",
                    email = "j.elith@unimelb.edu.au"))
Author: Roozbeh Valavi, Gurutzeta Guillera-Arroita, José Lahoz-Monfort and Jane Elith
Maintainer: Roozbeh Valavi <valavi.r@gmail.com>
Description: The blockCV package creates spatially or environmentally separated training and testing folds for cross-validation to provide a robust error estimation in spatially structured environments. It also investigates the effective range of spatial autocorrelation in continuous raster covariates to find an initial realistic distance band to separate training and testing datasets spatially. The distance band can be used for spatial blocking or buffering to create folds.
License: GPL-3
Encoding: UTF-8
LazyData: true
Depends:
  R (>= 3.4.1),
  ggplot2 (>= 2.2.1)
Imports:
  raster (>= 2.5-8),
  sp (>= 1.2-5),
  sf (>= 0.5-4),
  doParallel (>= 1.0.10),
  foreach (>= 1.4.3),
  automap (>= 1.0-14),
  RStoolbox (>= 0.1.8),
  shiny (>= 1.0.3),
  shinydashboard,
  methods,
  geosphere,
  progress,
  grid
RoxygenNote: 6.0.1
Suggests: knitr,
    rmarkdown,
    testthat
VignetteBuilder: knitr

```

-   URL for the package (the development repository, not a stylized html page):
https://github.com/rvalavi/blockCV
- Please indicate which category or categories from our [package fit policies](https://github.com/ropensci/onboarding/blob/master/policies.md#package-fit) this package falls under ***and why**(? (e.g., data retrieval, reproducibility. If you are unsure, we suggest you make a pre-submission inquiry.):

It falls in geospatial data category because the basic data input for the package is geospatial data and it produces folds to evaluate spatial prediction models.

-   Who is the target audience and what are scientific applications of this package?  

Ecologists, geographers and geospatial scientists. It provides a basis for evaluating spatial models (specifically species distribution models) and classification of remotely sensed data

-   Are there other R packages that accomplish the same thing? If so, how does
yours differ or meet [our criteria for best-in-category](https://github.com/ropensci/onboarding/blob/master/policies.md#overlap)?

As far as we know, there are two packages (sperrorest and ENMeval) which do a subset of what we do here, but our package is more comprehensive in relation to block cross-validation and more tailored to the breath of species distribution modelling applications. We have worked at providing outputs and functionalities likely required by species modellers, and believe our package fills an important gap in what is currently available.

-   If you made a pre-submission enquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.

### Requirements

Confirm each of the following by checking the box.  This package:

- [x] does not violate the Terms of Service of any service it interacts with. 
- [x] has a CRAN and OSI accepted license.
- [x] contains a README with instructions for installing the development version. 
- [x] includes documentation with examples for all functions.
- [x] contains a vignette with examples of its essential functions and uses.
- [x] has a test suite.
- [ ] has continuous integration, including reporting of test coverage, using services such as Travis CI, Coeveralls and/or CodeCov.
- [x] I agree to abide by [ROpenSci's Code of Conduct](https://github.com/ropensci/onboarding/blob/master/policies.md#code-of-conduct) during the review process and in maintaining my package should it be accepted.

#### Publication options

- [x] Do you intend for this package to go on CRAN?  
- [ ] Do you wish to automatically submit to the [Journal of Open Source Software](http://joss.theoj.org/)? If so:
    - [ ] The package has an **obvious research application** according to [JOSS's definition](http://joss.theoj.org/about#submission_requirements).
    - [ ] The package contains a `paper.md` matching [JOSS's requirements](http://joss.theoj.org/about#paper_structure) with a high-level description in the package root or in `inst/`.
    - [ ] The package is deposited in a long-term repository with the DOI: 
    - (*Do not submit your package separately to JOSS*)
- [x] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:
	- [x] The package is novel and will be of interest to the broad readership of the journal.
	- [x] The manuscript describing the package is no longer than 3000 words.
	- [x] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal.
	- (*Please do not submit your package separately to Methods in Ecology and Evolution*)

### Detail

- [x] Does `R CMD check` (or `devtools::check()`) succeed?  Paste and describe any errors or warnings:

- [x] Does the package conform to [rOpenSci packaging guidelines](https://github.com/ropensci/onboarding/blob/master/packaging_guide.md)? Please describe any exceptions:

- If this is a resubmission following rejection, please explain the change in circumstances:

- If possible, please provide recommendations of reviewers - those with experience with similar packages and/or likely users of your package - and their GitHub user names:
Dr. Nick Golding - goldingn

**Comment by karthik** [comment]
👋 @rvalavi 
Thank you for this submission. Unfortunately this package is out of scope for rOpenSci. We are unable to accept statistical/methods packages. We encourage you to seek review elsewhere and consider submitting to the [Journal of Open Source Software](http://joss.theoj.org/)

all the best.
