### ISSUE TITLE
Pre-submission: jstor

### ISSUE THREAD

**Issue by tklebel** [ropensci/onboarding#186]
The tool [Data for Research (DfR)](http://www.jstor.org/dfr/) by JSTOR is a valuable source for citation analysis and text mining. [`jstor`](https://github.com/tklebel/jstor) provides functions and suggests workflows for importing datasets from DfR. It was developed to deal with very large datasets which require an agreement with DfR, but can be used with smaller ones as well.

Currently, DfR offers three types of data:

1. metadata
2. n-grams
3. OCR/full-text

Within my own research I developed `jstor` to parse metadata, which comes in `xml`-files, and import full-texts (although importing full-text-files is trivial apart from encoding issues). From this data one can conduct citation analyses (citation data is scattered among metadata and full-text files), and any common kind of text-analysis with the complete text files. 

Very recently, DfR changed their delivery process. Due to this, other approaches like [JSTORr](https://github.com/benmarwick/JSTORr) are partly outdated. `jstor` is the only solution I know of which offers importing of JSTOR-metadata into a proper data-structure (i.e. `data.frame`s).

I would be interested in submitting `jstor` to rOpenSci for the category **data extraction**. Evidently, the goal is to parse `xml`-files to enable further analyis. Regarding overlap, `jstor` shares the name with `JSTORr`, which is the only thing they have in common regarding their scope.

Currently, `jstor` does not comply with some requirements of the packaging style guide, but these issues are not too difficult to resolve. The only issues with `goodpractice::gp()` are a test coverage of 94% and many lines with slightly more than 80 characters. (The tests are not in the public repo, since they build on files which I cannot share. This could be remedied, however.)

Please let me know, if you would be willing to accept a submission.

### Summary
The package allows the user to:

- import metadata 
- import full-text-files (although this wrapper might not be very useful for other users)

The package currently lacks support for metadata about book chapters, because this data was added to DfR only recently. If the package were to be considered by rOpenSci, I would be happy to add this feature.

**Comment by karthik** [comment]
👋 @tklebel 
The editorial team and I feel that this would be a very good addition to the suite under the data extraction category. We welcome a full submission when you're ready.  🙏 🎉

**Comment by tklebel** [comment]
@karthik thank you for your quick response and your interest! I’ll aim for a submission within 10-14 days.
