### ISSUE TITLE
Pre-Submission: rtweet

### ISSUE THREAD

**Issue by mkearney** [ropensci/onboarding#193]
I would like to make a pre-submission inquiry about [rtweet](https://github.com/mkearney/rtweet). I believe it would fall under **data retrieval**, because the package allows users to easily access and download Twitter data.

The bigger concern may be the target audience and the degree to which the package is "scientific". So, from my point of view, the target audience is anyone who wants to understand trends in user behaviors, public opinion, the dissemination of information, and/or features of communication as they relate to Twitter–a popular and uniquely public-facing social media platform. With that said, I am an academic researcher who studies digital/social media. So while **I** look at Twitter data and see a gold mine of scientific data, it's possible that most other people look at it and think of developing proprietary applications.

<hr>

*Note*: I started filling out the full-on submission template before I realized it wasn't a pre-submission inquiry template, so I included it (or what I've completed of it) below anyway.

<hr>

### Summary

-   What does this package do? (explain in 50 words or less):

It provides an R interface for interacting with Twitter's REST and stream APIs–with an emphasis on data retrieval interactions. Specifically, it formulates requests, manages authorization methods, automates navigation of paginated/cursored results, and wrangles response objects into data frames.

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: rtweet
Type: Package
Version: 0.6.16
Title: Collecting Twitter Data
Date: 2018-01-31
Authors@R: person("Michael W.", "Kearney", "", "kearneymw@missouri.edu", c("aut", "cre"))
Description: An implementation of calls designed to collect and
    organize Twitter data via Twitter's REST and stream Application
    Program Interfaces (API), which can be found at the following URL:
    <https://developer.twitter.com/en/docs>.
Depends:
    R (>= 3.1.0)
Imports:
    httr (>= 1.0.0),
    jsonlite,
    magrittr,
    openssl,
    readr,
    tibble,
    utils
License: MIT + file LICENSE
URL: https://CRAN.R-project.org/package=rtweet
BugReports: https://github.com/mkearney/rtweet/issues
Encoding: UTF-8
Suggests:
    ggplot2,
    knitr,
    rmarkdown,
    testthat,
    glue,
    magick,
    webshot,
    scales
VignetteBuilder: knitr
LazyData: yes
RoxygenNote: 6.0.1.9000
```

-   URL for the package (the development repository, not a stylized html page): https://github.com/mkearney/rtweet

- Please indicate which category or categories from our [package fit policies](https://github.com/ropensci/onboarding/blob/master/policies.md#package-fit) this package falls under ***and why**?

data retrieval, because the package allows users to easily access and download Twitter data.

-   Who is the target audience and what are scientific applications of this package?  

The target audience is anyone who wants to understand trends in user behaviors, public opinion, the dissemination of information, and/or features of communication as they relate to Twitter–a popular and uniquely public-facing social media platform. With that said, I am an academic researcher who studies Twitter. So while I look at Twitter data and see a gold mine of scientific data, it's possible that most other people look at it and think of developing proprietary applications. Scientific applications include [An Approach to Build a Database for Crimes in India Using Twitter](https://link.springer.com/chapter/10.1007/978-981-10-6427-2_13), [Social Media as a Tool to Look for People with Dementia Who Become Lost: Factors That Matter](https://scholarspace.manoa.hawaii.edu/handle/10125/50313), [Urban data and urban design: A data mining approach to architecture education](https://www.sciencedirect.com/science/article/pii/S0736585317303416), and my dissertation, [A network-based approach to estimating partisanship and analyzing change in polarization during the 2016 general election](https://www.researchgate.net/profile/Michael_Kearney11/project/Selective-Exposure-and-Network-Polarization-on-Twitter/attachment/5a19c106b53d2f6747c5effa/AS:564661725483008@1511637254295/download/00-manuscript-diss-final.pdf?context=ProjectUpdatesLog).

-   Are there other R packages that accomplish the same thing? If so, how does
yours differ or meet [our criteria for best-in-category](https://github.com/ropensci/onboarding/blob/master/policies.md#overlap)?

To date no other package interfaces with both REST and stream APIs. The twitteR package is most similar, but it has entered a stage of deprecation (I've agreed to carry the torch, so to speak, and he has agreed to send people my way). So, not only does twitteR not reflect some recent changes to Twitter's API (most notably the introduction of 'extended tweet' mode), but it lacks active maintenance thanks–in part–to me agreeing to hold down the Twitter API foRt.

**Comment by karthik** [comment]
👋 @mkearney
Thanks for your thoughtful inquiry. I agree that Twitter data is very useful for academic researchers and can be a significant data source when combined other sources. I also recognize that all APIs are somewhat fragile, so if Twitter changes their TOS or makes the API difficult to use, we can cross that bridge when the time comes. 

So yes, a full submission would be welcome. I'll close out this issue but please just copy over the template into a new one. 🙏
