### ISSUE TITLE
Pre-submission enquiry: spatialwarnings 

### ISSUE THREAD

**Issue by alexgenin** [ropensci/onboarding#197]
Hi all, 

We are currently working on a draft that we would like to submit to Methods in Ecology and Evolution. I'm approaching you for a possible software review (following [1]), but I'm unsure whether it meets the scope of the collaboration between rOpenSci and MEE. 

Our package facilitates a type of spatial data analysis that tries to measure the degradation of ecosystems from aerial images. Ecological research has produced a variety of metrics that capture a certain aspect of the spatial structure of an ecosystem and are thought to reflect how degraded it is or how close it is to shifting to a different state. 

The idea of `spatialwarnings` is to provide a common three-step workflow to work with all these metrics on empirical data. The basic usage is to start from a list of `matrix` objects in R, (i) compute the indicators, (ii) review their significance and (iii) display the results through classical generic functions (plot, summary, etc.). A more complete description along with a concrete example is given on the package homepage: 

  https://github.com/spatial-ews/spatialwarnings

Our package is on CRAN [2] but the github repo has a more up-to-date version with better documentation and more features. 

The package would surely benefit from a review, but I'm not sure it fits the scope of the collaboration between MEE and rOpenSci. It provides a common interface to carry out several statistical analyses (hence improving reproducibility), but at the same time it's not centered around any of the main topics in the policies (maybe geospatial data?). 

Do you think this would be fit for a review here ? 

Thanks for your work ! 

Alex (@alexgenin)

[1] https://methodsblog.wordpress.com/2017/11/29/software-review/
[2] https://cran.r-project.org/web/packages/spatialwarnings/index.html

**Comment by maelle** [comment]
@alexgenin, thanks for your submission! We have discussed it and regret to say that it is out of scope since we do not support statistical methods. 

We appreciate that you submitted your package, and hope you might submit another one in the future!

**Comment by alexgenin** [comment]
Very good, I completely understand the decision. Thanks for taking the time to look into this!
