### ISSUE TITLE
meta questions

### ISSUE THREAD

**Issue by karthik** [ropensci/onboarding#2]
> Who has/will contribute to this package?

Do we really need a will contribute part at this stage? Why does this matter now?

> Are you willing to follow the rOpenSci policies (link), including transferring your repo to the rOpenSci GitHub organization account?

Can we list concrete things to check off here?

>  Are you willing to follow the [rOpenSci packaging guidelines](https://github.com/ropensci/packaging_guide? If you have disagreements with them, explain.

This seems like a rather big question for a binary answer. I'm not even sure most current rOpenSci packages can safely answer yes to those. Should we break those down here?

**Comment by richfitz** [comment]
The question:

> Are you willing to follow the rOpenSci policies (link), including transferring your repo to the rOpenSci GitHub organization account?

Seems like we might want to flag these things will come in the README (or in a longer "process" document that includes things like setting up the slack links) and then once we have provisional acceptance, tag the issue to indicate that and paste in a set of check boxes for this sort of stuff?

**Comment by sckott** [comment]
@karthik 

> Do we really need a will contribute part at this stage? Why does this matter now?

I guess not, just wondering if we should get a sense for who's involved, not really needed

> Can we list concrete things to check off here? (wrt policies)

yes, once we agree on the policies, let's just make a bulleted list with checkboxes, or one checkbox to agree to all

On packaging guidelines  -we could just say _Are there any you disagree with? If so, explain_ - and if we agree to let that thing slide, cool cool

**Comment by karthik** [comment]
Should we create a `template.md` and put things there for people to copy and paste into an issue? We can link to the raw version of that file (so boxes and such won't get rendered) making it a bit easier.

**Comment by sckott** [comment]
yeah, link to raw is probably best

**Comment by karthik** [comment]
Just realized we could skip the `template.md` and stick everything in `contributing.md` instead.

**Comment by sckott** [comment]
sure, that works

**Comment by sckott** [comment]
@richfitz to which page?

**Comment by karthik** [comment]
@richfitz Good idea, but I'm ambivalent on adding this to contributing.md. We generally don't want to add post acceptance instructions here (same reason a journal doesn't send you printer instructions with submitting guidelines). 
Also worried that even though the html is trivial, it's not exactly obvious what one needs to do to edit and what the tags mean etc.

**Comment by richfitz** [comment]
OK, cool.  You added it as a thing to do on #6 but I don't know where to edit and thought it was a general thing that the contributor would add.

**Comment by karthik** [comment]
Ah, sorry. I'll add a wiki entry for the post acceptance checklist.
