### ISSUE TITLE
Remove me

### ISSUE THREAD

**Issue by nujcharee** [ropensci/onboarding#202]

**Comment by noamross** [comment]
Hi @nujcharee, I think what you're trying to do is stop being notified of conversations in this repo.  You can do that via the "unwatch" button on the upper right:

<img width="369" alt="screen shot 2018-03-11 at 7 22 57 pm" src="https://user-images.githubusercontent.com/571752/37259818-b3f0b9b8-2561-11e8-8175-a9a8e3758493.png">

**Comment by nujcharee** [comment]
Hi there, I was reviewing a package but I foolishly put my review in a wrong window. I didn’t know how to delete it. Do apologise. I had many windows opened to read guidelines, templates etc....:)

**Comment by maelle** [comment]
No problem 😉
