### ISSUE TITLE
presubmission inquiry: SummarizedBenchmark

### ISSUE THREAD

**Issue by pkimes** [ropensci/onboarding#204]
We recently went through the review process with Bioconductor, but I was hoping to get more feedback, and thought rOpenSci might be a good fit for our package. I wasn't sure, so I wanted to make a pre-submission inquiry. Thanks for taking a look!

For reference:
- [Bioconductor Submission thread](https://github.com/Bioconductor/Contributions/issues/651)
- [Bioconductor devel page (with vignettes)](https://bioconductor.org/packages/devel/bioc/html/SummarizedBenchmark.html)

### Summary

-   What does this package do? (explain in 50 words or less):

The package provides classes and methods for defining, executing, and comparing computational methods in R.

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: SummarizedBenchmark
Type: Package
Title: Classes and methods for performing benchmark comparisons
Version: 0.99.5
Author: Alejandro Reyes <alejandro.reyes.ds@gmail.com>, 
        Patrick Kimes <patrick.kimes@gmail.com>
Maintainer: Alejandro Reyes <alejandro.reyes.ds@gmail.com>, 
            Patrick Kimes <patrick.kimes@gmail.com>
Description: This package defines the BenchDesign and SummarizedBenchmark 
    classes for building, executing, and evaluating benchmark experiments of computational
    methods. The SummarizedBenchmark class extends the RangedSummarizedExperiment 
    object, and is designed to provide infrastructure to store and compare the results of 
    applying different methods to a shared data set. This class provides an integrated interface 
    to store metadata such as method parameters and software versions as well as ground
    truths (when these are available) and evaluation metrics.
biocViews: Software, Infrastructure
Depends: R (>= 3.5), tidyr, SummarizedExperiment, 
         S4Vectors, BiocGenerics, methods, UpSetR, rlang, 
         stringr, utils, BiocParallel, ggplot2, mclust, dplyr
Suggests: iCOBRA, BiocStyle, knitr, magrittr, IHW, 
          qvalue, testthat, DESeq2, edgeR, limma, tximport, 
          readr, scRNAseq, splatter, scater, rnaseqcomp, 
          biomaRt
License: GPL (>= 3)
Encoding: UTF-8
LazyData: true
VignetteBuilder: knitr
RoxygenNote: 6.0.1
```

-   URL for the package (the development repository, not a stylized html page):

https://github.com/areyesq89/SummarizedBenchmark

- Please indicate which category or categories from our [package fit policies](https://github.com/ropensci/onboarding/blob/master/policies.md#package-fit) this package falls under ***and why**(? (e.g., data retrieval, reproducibility. If you are unsure, we suggest you make a pre-submission inquiry.):

**reproducibility**: By providing a simple way to define and execute benchmarks, one of the main aims of the package is to make comparisons of methods in R easier to reproduce.

-   Who is the target audience and what are scientific applications of this package?  

The package is targeted at regular R users interested in comparing different methods for analyzing their data, as well as R developers interested in benchmarking their own methods against other methods.

-   Are there other R packages that accomplish the same thing? If so, how does
yours differ or meet [our criteria for best-in-category](https://github.com/ropensci/onboarding/blob/master/policies.md#overlap)?

A similar package for benchmarking methods in R exists on GitHub [here (`dscr`)](https://github.com/stephens999/dscr). While the basic structure of the two packages are similar, there are a few major differences:
1. development of `dscr` appears to have stopped prematurely.
2. the core of `dscr` is an `environment` object, while `SummarizedBenchmark` works with standard lists and an extension of the Bioconductor `SummarizedExperiment` class, making it easier to use.
3. SummarizedBenchmark modularizes the steps of designing, executing, and storing benchmarking results, which we believe to be a more intuitive and flexible framework that what is used in `dscr`.

Thanks! Looking forward to any feedback.

**Comment by karthik** [comment]
👋 @pkimes
The editors and I have discussed this submission and find that it is outside our scope. A performance benchmarking isn't part of our reproducibility category. 

best,
Karthik

**Comment by pkimes** [comment]
@karthik, thanks for taking a look!
