### ISSUE TITLE
presubmission inquiry: cptcity

### ISSUE THREAD

**Issue by ibarraespinosa** [ropensci/onboarding#205]
### Summary

-   What does this package do? (explain in 50 words or less):
cpt-city is a web archive (http://soliton.vm.bytemark.co.uk/pub/cpt-city/index.html) of colour palettes. The R package cptcity brings 7140 colour palettes from this web archive into R. It has three functions:
- cpt(). To select the colour palette and number.
- find_cpt(). To search colour palettes by name, e.g.: "radar", "rain", "land".
- lucky(). To randomly choose a colour palette. (it is very funny).

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: cptcity
Type: Package
Title: 'cpt-city' Colour Gradients
Version: 1.0.2
Authors@R: c(
  person(given = "Sergio", family = "Ibarra-Espinosa",
        role = c("aut", "cre"),
        email = "sergio.ibarra@usp.br",
        comment = c(ORCID = "0000-0002-3162-1905"))) 
Description: Incorporates colour gradients from the 'cpt-city' web archive available at <http://soliton.vm.bytemark.co.uk/pub/cpt-city/>. 
Depends: R (>= 2.10)
Imports: grDevices
License: GPL-3
URL: https://github.com/ibarraespinosa/cptcity
BugReports: https://github.com/ibarraespinosa/cptcity/issues/
Encoding: UTF-8
LazyData: true
RoxygenNote: 6.0.1
Suggests:
    covr,
    testthat

```

-   URL for the package (the development repository, not a stylized html page):
https://github.com/ibarraespinosa/cptcity and CRAN: https://CRAN.R-project.org/package=cptcity
- Please indicate which category or categories from our [package fit policies](https://github.com/ropensci/onboarding/blob/master/policies.md#package-fit) this package falls under ***and why**(? (e.g., data retrieval, reproducibility. If you are unsure, we suggest you make a pre-submission inquiry.):

[e.g., "data extraction, because the package parses a scientific data file format"]

-   Who is the target audience and what are scientific applications of this package?  
Any R use who want to use colour palettes from cptcity.

-   Are there other R packages that accomplish the same thing? If so, how does
yours differ or meet [our criteria for best-in-category](https://github.com/ropensci/onboarding/blob/master/policies.md#overlap)?

I believe that some package have implemented some specific colour palettes, for instance, the package 'viridis' has 4 colour scales and 'inferno' is named 'mpl_inferno' in cptcity. However, this package brings the whole cpt-city web archive. Even more, this package includes COPYING.XML files of all colour palettes at the 'inst' folder, therefore, the authorship is respected.

-   If you made a pre-submission enquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.

### Requirements

Confirm each of the following by checking the box.  This package:

- [ x] does not violate the Terms of Service of any service it interacts with. 
- [ x] has a CRAN and OSI accepted license.
- [ x] contains a README with instructions for installing the development version. 
- [ x] includes documentation with examples for all functions.
- [ x] contains a vignette with examples of its essential functions and uses.
- [ x] has a test suite.
- [ x] has continuous integration, including reporting of test coverage, using services such as Travis CI, Coveralls and/or CodeCov.
- [ x] I agree to abide by [ROpenSci's Code of Conduct](https://github.com/ropensci/onboarding/blob/master/policies.md#code-of-conduct) during the review process and in maintaining my package should it be accepted.

#### Publication options

- [ x] Do you intend for this package to go on CRAN?  
- [ x] Do you wish to automatically submit to the [Journal of Open Source Software](http://joss.theoj.org/)? If so:
    - [ ] The package has an **obvious research application** according to [JOSS's definition](http://joss.theoj.org/about#submission_requirements).
    - [ ] The package contains a `paper.md` matching [JOSS's requirements](http://joss.theoj.org/about#paper_structure) with a high-level description in the package root or in `inst/`.
    - [ ] The package is deposited in a long-term repository with the DOI: 
    - (*Do not submit your package separately to JOSS*)
- [ ] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:
    - [ ] The package is novel and will be of interest to the broad readership of the journal. 
    - [ ] The manuscript describing the package is no longer than 3000 words.
    - [ ] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal (see [MEE's Policy on Publishing Code](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/journal-resources/policy-on-publishing-code.html))
    - (*Scope: Do consider MEE's [Aims and Scope](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/aims-and-scope/read-full-aims-and-scope.html) for your manuscript. We make no gaurantee that your manuscript willl be within MEE scope.*)
    - (*Although not required, we strongly recommend having a full manuscript prepared when you submit here.*)
    - (*Please do not submit your package separately to Methods in Ecology and Evolution*)

### Detail

- [ x] Does `R CMD check` (or `devtools::check()`) succeed?  Paste and describe any errors or warnings:

- [ ]x Does the package conform to [rOpenSci packaging guidelines](https://github.com/ropensci/onboarding/blob/master/packaging_guide.md)? Please describe any exceptions:

- If this is a resubmission following rejection, please explain the change in circumstances:

- If possible, please provide recommendations of reviewers - those with experience with similar packages and/or likely users of your package - and their GitHub user names:

**Comment by karthik** [comment]
👋 @ibarraespinosa
Thanks for the submission. The other editors and I have discussed this and will unfortunately have to decline this as out of scope. It is also out of scope for JOSS.
