### ISSUE TITLE
presubmission inquiry: codebook

### ISSUE THREAD

**Issue by rubenarslan** [ropensci/onboarding#206]
Presubmission inquiry following [Twitter contact](https://twitter.com/ma_salmon/status/977192303751323649) with @maelle 

### Summary

-   What does this package do? (explain in 50 words or less):
Generate reproducible codebooks from data and metadata. The package relies on rmarkdown partials to generate HTML, PDF, and Word documents. Codebooks are also available as tables (CSV, Excel, etc.). HTML codebooks include machine-readable JSON-LD metadata by default. Metadata (var/value/missing labels) as imported by haven or rio is used.

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: codebook
Title: Automatic Codebooks from Survey Metadata Encoded in Attributes
Description: Easily automate the following tasks to describe data frames: 
  computing reliabilities (internal consistencies, retest, multilevel) for psychological scales, 
  summarise the distributions of scales and items graphically and using descriptive statistics,
  combine this information with metadata (such as item labels and labelled values) that is derived from R attributes.
  To do so, the package relies on 'rmarkdown' partials, so you can generate HTML, PDF, and Word documents. Codebooks
  are also available as tables (CSV, Excel, etc.).
Version: 0.5.8.9000
Authors@R: person("Ruben", "Arslan", email = "ruben.arslan@gmail.com", role = c("aut", "cre"))
Depends: R (>= 3.0.1)
URL: https://github.com/rubenarslan/codebook
BugReports: https://github.com/rubenarslan/codebook/issues
License: MIT + file LICENSE
Imports:
		stats,
		methods,
		graphics,
		utils,
		rmarkdown,
    ggplot2,
    stringr,
    psych,
    likert,
    knitr,
    rlang,
    dplyr,
    tidyr,
    pander,
    skimr,
    DT,
    future,
    haven,
    readr,
    mice,
    tibble,
    purrr
Suggests:
  testthat,
  lme4,
  roxygen2
Encoding: UTF-8
LazyData: true
RoxygenNote: 6.0.1
Roxygen: list(markdown = TRUE) 
VignetteBuilder: knitr
```

-   URL for the package (the development repository, not a stylized html page):
https://github.com/rubenarslan/codebook

- Please indicate which category or categories from our [package fit policies](https://github.com/ropensci/onboarding/blob/master/policies.md#package-fit) this package falls under ***and why**(? (e.g., data retrieval, reproducibility. If you are unsure, we suggest you make a pre-submission inquiry.):

data deposition, because the package helps generate human and machine-readable codebooks for datasets.

-   Who is the target audience and what are scientific applications of this package?  

     - People who want to share data or share information about data. Probably mainly social scientists who have smaller amounts of data to share and wouldn't be willing to learn about other, more complex approaches.
     - Users who have received data and want to learn about the dataset, get an overview of included variables, together with metadata.
     - The scientific use here would be to get more metadata out in the open (both in the sense of putting in on the web and using open, standard formats for metadata like JSON-LD). Scientific applications would then be better discovery and interoperability of small datasets (for which the codebook pkg helps only with a small, but necessary preliminary step).

-   Are there other R packages that accomplish the same thing? If so, how does
yours differ or meet [our criteria for best-in-category](https://github.com/ropensci/onboarding/blob/master/policies.md#overlap)?

     - Yes
          - [dataMaid](https://github.com/ekstroem/dataMaid) has a codebook function which also uses rmarkdown. I'm in contact with them, and they plan to continue to focus more on error detection. We might collaborate on `codebook`. Features that `codebook` has that `dataMaid` doesn't have: reliability computation, tabular metadata output with `skimr` summaries, machine-readable JSON-LD metadata, embeddable rmarkdown partials.
          - [codebookr](https://github.com/petebaker/codebookr) appears no longer to be under active development and focuses more on extracting structured metadata.
          - [memisc](http://github.com/melff/memisc/) has a codebook function. It focuses on printing codebooks to the console, but also generates HTML. It doesn't generate graphs, or machine-readable metadata and doesn't use the rmarkdown partial approach, which I consider more powerful. Also, memisc appears to be unable to deal with datetimes and labelled vectors.
          - [DDIwR](https://cran.r-project.org/web/packages/DDIwR/index.html) focuses on importing and exporting DDI. I am in contact with author, we'll probably make it possible to generate & embed DDI when generating codebooks. 
          - [r2ddi](https://github.com/ddionrails/r2ddi/) is inactive (personal communication: dev. switched to python)

**Comment by karthik** [comment]
Quick update. We are still discussing the submission and will get back to you shortly.

**Comment by rubenarslan** [comment]
Thanks. I updated the description about DDIwR, because I since made contact with Adrian Dusa @dusadrian.

**Comment by noamross** [comment]
Sorry for the delay, @rubenarslan. This got lost in the shuffle as we rotated editors.  Ultimately, we decided that **codebook** doesn't fall into our scope.  The data deposition category is primarily for uploading data to scientific repositories and generating appropriate metadata for that purpose.  **codebook** falls more into the category of literate programming or data exploration tools to produce human-readable outputs from data, which we don't support anymore because we've decided that that we can't really judge a 'best' way to look at outputs.

Of course, being out-of-scope for us doesn't mean the package isn't useful!  I think this kind of thing is very handy.  We encourage you to submit to other options like JOSS, where I believe this would be in-scope.

**Comment by rubenarslan** [comment]
@noamross To me the human-readable part is more a means to the end of getting machine-readable and Google-able metadata out there and into repositories. But it's definitely a more minor part of what the package actually does. I was hoping to benefit from the metadata expertise of some of the reviewers here, but I guess/hope some of the same people review for JOSS.

**Comment by noamross** [comment]
Yes, there is overlap in both reviewers and editors between us and JOSS. We'll tell the JOSS editors to look out for the package to make sure the right folks handle it.
