### ISSUE TITLE
package submission for review

### ISSUE THREAD

**Issue by peter0083** [ropensci/onboarding#211]
### Summary

-   What does this package do? (explain in 50 words or less):

It is an API wrapper package for Lufthansa Open API

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: LufthansaR
Title: Lufthansa API Wrapper
Version: 0.0.0.9000
Authors@R: c(
    person("Amy", "Goldlist", email = "amygoldlist@gmail.com", role = c("aut")),
    person("Peter", "Lin", email = "peter.tingyao@alumni.ubc.ca", role = c("aut", "trl", "cre")),
    person("Joe", "Sastrillo", email = "jomar.sastrillo@gmail.com", role = c("aut")),
    person("Hatice", "Cavusoglu", email = "hntek@yahoo.com", role = c("aut"))
    )
Maintainer: Peter Lin <peter.tingyao@alumni.ubc.ca>
Description: This package is an API wrapper for the Lufthansa Open API.
Depends: R (>= 3.4.2)
License: MIT + file LICENSE
Encoding: UTF-8
LazyData: true
Imports:
  httr,
  glue (>= 1.2.0),
  lubridate
RoxygenNote: 6.0.1
Suggests: testthat,
    knitr,
    rmarkdown
VignetteBuilder: knitr

```

-   URL for the package (the development repository, not a stylized html page): 

https://github.com/peter0083/LufthansaR

- Please indicate which category or categories from our [package fit policies](https://github.com/ropensci/onboarding/blob/master/policies.md#package-fit) this package falls under ***and why**(? (e.g., data retrieval, reproducibility. If you are unsure, we suggest you make a pre-submission inquiry.):

[e.g., "data extraction, because the package parses a scientific data file format"]

data retrieval, because the package provides an easier access to open data

-   Who is the target audience and what are scientific applications of this package?  

-   Are there other R packages that accomplish the same thing? If so, how does
yours differ or meet [our criteria for best-in-category](https://github.com/ropensci/onboarding/blob/master/policies.md#overlap)?

-   If you made a pre-submission enquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.

### Requirements

Confirm each of the following by checking the box.  This package:

- [X] does not violate the Terms of Service of any service it interacts with. 
- [X] has a CRAN and OSI accepted license.
- [X] contains a README with instructions for installing the development version. 
- [X] includes documentation with examples for all functions.
- [X] contains a vignette with examples of its essential functions and uses.
- [X] has a test suite.
- [X] has continuous integration, including reporting of test coverage, using services such as Travis CI, Coveralls and/or CodeCov.
- [X] I agree to abide by [ROpenSci's Code of Conduct](https://github.com/ropensci/onboarding/blob/master/policies.md#code-of-conduct) during the review process and in maintaining my package should it be accepted.

#### Publication options

- [X] Do you intend for this package to go on CRAN?  
- [ ] Do you wish to automatically submit to the [Journal of Open Source Software](http://joss.theoj.org/)? If so:
    - [ ] The package has an **obvious research application** according to [JOSS's definition](http://joss.theoj.org/about#submission_requirements).
    - [ ] The package contains a `paper.md` matching [JOSS's requirements](http://joss.theoj.org/about#paper_structure) with a high-level description in the package root or in `inst/`.
    - [ ] The package is deposited in a long-term repository with the DOI: 
    - (*Do not submit your package separately to JOSS*)
- [ ] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:
    - [ ] The package is novel and will be of interest to the broad readership of the journal. 
    - [ ] The manuscript describing the package is no longer than 3000 words.
    - [ ] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal (see [MEE's Policy on Publishing Code](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/journal-resources/policy-on-publishing-code.html))
    - (*Scope: Do consider MEE's [Aims and Scope](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/aims-and-scope/read-full-aims-and-scope.html) for your manuscript. We make no gaurantee that your manuscript willl be within MEE scope.*)
    - (*Although not required, we strongly recommend having a full manuscript prepared when you submit here.*)
    - (*Please do not submit your package separately to Methods in Ecology and Evolution*)

### Detail

- [ ] Does `R CMD check` (or `devtools::check()`) succeed?  Paste and describe any errors or warnings:

```
See
  ‘/private/var/folders/g5/zxkqsl55307bwv3hwz5nmnpr0000gn/T/RtmpWnEf0h/LufthansaR.Rcheck/00check.log’
for details.

R CMD check results
2 errors | 0 warnings | 2 notes
checking examples ... ERROR
Running examples in ‘LufthansaR-Ex.R’ failed
The error most likely occurred in:

> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: get_flight_status_arrival
> ### Title: GET Flight Status at Arrival Airport
> ### Aliases: get_flight_status_arrival
> 
> ### ** Examples
> 
> get_flight_status_departure(airport = "YVR", fromDateTime = "2018-04-13T00:00")
Error in get_creds_from_server() : 
  Problem with calling the API - response: invalid_client
Calls: get_flight_status_departure -> get_token -> get_creds_from_server
Execution halted

checking tests ... ERROR
  Running ‘testthat.R’
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  3: stop("Problem with calling the API - response: ", httr::content(response))
  
  ── 2. Error: (unknown) (@test_user_cred.R#8)  ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  Problem with calling the API - response: invalid_client
  1: get_token() at testthat/test_user_cred.R:8
  2: get_creds_from_server()
  3: stop("Problem with calling the API - response: ", httr::content(response))
  
  ══ testthat results  ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
  OK: 0 SKIPPED: 1 FAILED: 2
  1. Error: (unknown) (@test_functions.R#8) 
  2. Error: (unknown) (@test_user_cred.R#8) 
  
  Error: testthat unit tests failed
  Execution halted

checking top-level files ... NOTE
Non-standard files/directories found at top level:
  ‘CODE_OF_CONDUCT.md’ ‘CONTRIBUTING.md’ ‘ISSUE_TEMPLATE.md’
  ‘Thumbs.db’ ‘image’ ‘package_logo.Rmd’

checking R code for possible problems ... NOTE
airport: no visible global function definition for ‘content’
Undefined global functions or variables:
  content
```

- [x] Does the package conform to [rOpenSci packaging guidelines](https://github.com/ropensci/onboarding/blob/master/packaging_guide.md)? Please describe any exceptions:

- If this is a resubmission following rejection, please explain the change in circumstances:

- If possible, please provide recommendations of reviewers - those with experience with similar packages and/or likely users of your package - and their GitHub user names:

**Comment by noamross** [comment]
Thank you for your submission, @peter0083. Unfortunately, this package is not of sufficient scientific application to fit in our scope.

**Comment by peter0083** [comment]
Thank you for the feedback Noam!
