### ISSUE TITLE
Submission: openbahn

### ISSUE THREAD

**Issue by ottlngr** [ropensci/onboarding#221]
### Summary

-   The package provides an easy way to query the open timetable API of the German railway company Deutsche Bahn (DB). Basically the package (or the API) supply 3 core functions, which build upon each other: 
    - find a train station with its coordinates
    - retrieve arrival and departure boards
    - retrieve additional information to certain routes

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: openbahn
Type: Package
Title: Query the Deutsche Bahn Timetable API
Version: 1.0.0
Authors@R: person("Philipp", "Ottolinger", email = "philipp@ottolinger.de", "role" = c("aut", "cre"))
Maintainer: Philipp Ottolinger <philipp@ottolinger.de>
Description: This package queries the Deutsche Bahn Timetable API which covers the German long distance traffic. Each API endpoint is handled by its own function providing searches for locations, retrieval of arrival and departure boards as well as getting further details on specific journeys.
URL: https://github.com/ottlngr/openbahn
BugReports: http://github.com/ottlngr/openbahn/issues
References: http://data.deutschebahn.com/dataset/api-fahrplan
License: GPL-3
Encoding: UTF-8
LazyData: true
RoxygenNote: 6.0.1
Depends: R (>= 2.10)
Imports: httr, jsonlite
Suggests: testthat,
    covr,
    knitr,
    rmarkdown,
    dplyr,
    ggplot2,
    ggmap
VignetteBuilder: knitr
```

-   URL for the package (the development repository, not a stylized html page): 

https://github.com/ottlngr/openbahn

- Please indicate which category or categories from our [package fit policies](https://github.com/ropensci/onboarding/blob/master/policies.md#package-fit) this package falls under ***and why**(? (e.g., data retrieval, reproducibility. If you are unsure, we suggest you make a pre-submission inquiry.):

data retrieval, because the package retrieves data from an API

-   Who is the target audience and what are scientific applications of this package?  

Everyone who wants to analyze the German long dinstance railway traffic and the network of train stations. Especially valuable in combination with maps and other spatial tasks.

-   Are there other R packages that accomplish the same thing? If so, how does
yours differ or meet [our criteria for best-in-category](https://github.com/ropensci/onboarding/blob/master/policies.md#overlap)?

Not to my knowledge.

-   If you made a pre-submission enquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.

### Requirements

Confirm each of the following by checking the box.  This package:

- [x] does not violate the Terms of Service of any service it interacts with. 
- [x] has a CRAN and OSI accepted license.
- [x] contains a README with instructions for installing the development version. 
- [x] includes documentation with examples for all functions.
- [x] contains a vignette with examples of its essential functions and uses.
- [x] has a test suite.
- [x] has continuous integration, including reporting of test coverage, using services such as Travis CI, Coveralls and/or CodeCov.
- [x] I agree to abide by [ROpenSci's Code of Conduct](https://github.com/ropensci/onboarding/blob/master/policies.md#code-of-conduct) during the review process and in maintaining my package should it be accepted.

#### Publication options

- [x] Do you intend for this package to go on CRAN?  
- [ ] Do you wish to automatically submit to the [Journal of Open Source Software](http://joss.theoj.org/)? If so:
    - [ ] The package has an **obvious research application** according to [JOSS's definition](http://joss.theoj.org/about#submission_requirements).
    - [ ] The package contains a `paper.md` matching [JOSS's requirements](http://joss.theoj.org/about#paper_structure) with a high-level description in the package root or in `inst/`.
    - [ ] The package is deposited in a long-term repository with the DOI: 
    - (*Do not submit your package separately to JOSS*)
- [ ] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:
    - [ ] The package is novel and will be of interest to the broad readership of the journal. 
    - [ ] The manuscript describing the package is no longer than 3000 words.
    - [ ] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal (see [MEE's Policy on Publishing Code](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/journal-resources/policy-on-publishing-code.html))
    - (*Scope: Do consider MEE's [Aims and Scope](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/aims-and-scope/read-full-aims-and-scope.html) for your manuscript. We make no gaurantee that your manuscript willl be within MEE scope.*)
    - (*Although not required, we strongly recommend having a full manuscript prepared when you submit here.*)
    - (*Please do not submit your package separately to Methods in Ecology and Evolution*)

### Detail

- [x] Does `R CMD check` (or `devtools::check()`) succeed?  Paste and describe any errors or warnings:

``` 
R CMD check results
0 errors | 0 warnings | 0 notes
```

- [x] Does the package conform to [rOpenSci packaging guidelines](https://github.com/ropensci/onboarding/blob/master/packaging_guide.md)? Please describe any exceptions:

- If this is a resubmission following rejection, please explain the change in circumstances:

- If possible, please provide recommendations of reviewers - those with experience with similar packages and/or likely users of your package - and their GitHub user names:

The reviewers should be familiar with web APIs, especially with the use of `httr`.

**Comment by noamross** [comment]
Thank you for your submission, @ottlngr . Unfortunately, this package is not of sufficient scientific application to fit in our scope.  (We made a similar decision recently with an [airline data package submission](https://github.com/ropensci/onboarding/issues/211), deciding that a single company transit API doesn't quite reach our target of scientific applications.)

I note from twitter that you are, working working on somepackages related from the webservices API like **tinycc**.  This is great!  I just wanted to note that not everything there or that we work on is in-scope for our onboarding process - I don't believe **tinycc** would be.  Some stuff on that wiki predates or has developed independently of our package review scope. This is something [we recently discussed on our forum](https://discuss.ropensci.org/t/dataspice-codebook-and-ropensci-scope/1179/2?u=noamross)

Finally, a question:  I see you use the `References:` field in your DESCRIPTION file.  I think this is an undocumented field, and as far as I can tell [only 3 packages on CRAN use it](https://github.com/search?utf8=%E2%9C%93&q=user%3Acran+filename%3ADESCRIPTION+references&type=).  Where did you pick it up?  I wonder if its something we should encourage more use of.

**Comment by ottlngr** [comment]
> Unfortunately, this package is not of sufficient scientific application to fit in our scope. (We made a similar decision recently with an airline data package submission, deciding that a single company transit API doesn't quite reach our target of scientific applications.)

Indeed.

>  I just wanted to note that not everything there or that we work on is in-scope for our onboarding process

That is totally clear!

>  I see you use the References: field in your DESCRIPTION file. I think this is an undocumented field, and as far as I can tell only 3 packages on CRAN use it. Where did you pick it up? I wonder if it is something we should encourage more use of.

I can't remember where I picked that up but I can remember that I looked for a suitable field for such a purpose. I liked the idea of linking to the API specification in the DESCRIPTION because the package is some kind of a "replica" of the API and its functionally derives straight from the API.
