### ISSUE TITLE
 Pre-submission inquiry: datastructures

### ISSUE THREAD

**Issue by dirmeier** [ropensci/onboarding#225]
Hello,

I would like to submit the _datastructures_ package, if it fits your policy and would be usefull. The package implements some data structures that are currently missing on R but sometimes needed for some algorithms. Some of the datastructures are:

- Fibonacci and binomial heaps,
- queues and stacks,
- bimaps and multimaps.

datastructures is already on [CRAN](https://cran.r-project.org/web/packages/datastructures/index.html), I hope this would not be a problem. Here is the github link: https://github.com/dirmeier/datastructures

Thank you and best regards,
Simon

### Summary

-   What does this package do? (explain in 50 words or less):

datastructures implements advanced data structures using Boost and Rcpp modules.

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: datastructures
Type: Package
Title: Implementation of Core Data Structures
Version: 0.2.6
Date: 2018-04-22
Authors@R: person("Simon", "Dirmeier",
                  email = "simon.dirmeier@web.de",
                  role = c("aut", "cre"))
Maintainer: Simon Dirmeier <simon.dirmeier@web.de>
Description: Implementation of advanced data structures such as hashmaps,
    heaps, or queues. Advanced data structures are essential
    in many computer science and statistics problems, for example graph
    algorithms or string analysis. The package uses 'Boost' and 'STL' data
    types and extends these to R with 'Rcpp' modules.
URL: https://github.com/dirmeier/datastructures
BugReports: https://github.com/dirmeier/datastructures/issues
License: GPL-3
Encoding: UTF-8
Depends:
    R (>= 3.3),
    Rcpp
Suggests:
    testthat,
    knitr,
    rmarkdown,
    lintr
VignetteBuilder: knitr
RoxygenNote: 6.0.1
SystemRequirements: C++11
Imports:
    methods,
    purrr
LinkingTo:
    Rcpp,
    BH
NeedsCompilation: yes
Collate: 
    'checks.R'
    'datastructures-package.R'
    'methods_insert.R'
    'methods_size.R'
    'methods_pop.R'
    'methods_peek.R'
    'ds_deque.R'
    'ds_deque_queue.R'
    'ds_deque_stack.R'
    'methods_values.R'
    'methods_decrease.R'
    'methods_handle.R'
    'ds_heap.R'
    'ds_heap_binomial.R'
    'ds_heap_fibonacci.R'
    'methods_head.R'
    'ds_map.R'
    'methods_keys.R'
    'methods_get.R'
    'ds_map_bimap.R'
    'ds_map_unordered.R'
    'ds_map_hashmap.R'
    'ds_map_multimap.R'
'zzz.R'
```

**Comment by noamross** [comment]
Thanks for your submission, @dirmeier!  This is a neat package, and I may use it for some things myself.  However, I'm afraid it's out of scope for our review, as we limit ourselves to [packages supporting the research data lifecycle](https://github.com/ropensci/onboarding/blob/master/policies.md#aims-and-scope).  This would be a good submission for [The Journal of Open Source Software](http://joss.theoj.org/) .

**Comment by dirmeier** [comment]
Wow, thanks for the quick feedback and thanks for the JOSS hint :). I think that's a great idea.
Regards,
Simon
