### ISSUE TITLE
Pre-submission inquiry: repvar

### ISSUE THREAD

**Issue by zkamvar** [ropensci/onboarding#229]
### Summary

-   What does this package do? (explain in 50 words or less):

The *repvar* package finds the minimum set of samples that **rep**resents all **var**iables in a sparse matrix. This is useful for determining a subset of samples needed for positive controls in population genetic studies using microsatellite markers.

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: repvar
Type: Package
Title: Extract Samples to Represent All Variables
Version: 0.1.0
Depends: R (>= 3.1.0)
BugReports: https://github.com/zkamvar/repvar/issues
Imports: stats, graphics
Authors@R: c(person(c("Zhian", "N."), "Kamvar", role = c("cre", "aut"),
    email = "zkamvar@gmail.com", comment = c(ORCID = "0000-0003-1458-7108")),
    person(c("Sydney", "E."), "Everhart", role = c("ctb", "dtc"),
    email = "everhart@unl.edu", comment = c(ORCID = "0000-0002-5773-1280")))
Maintainer: Zhian N. Kamvar <zkamvar@gmail.com>
Description: In population genetics, it's not uncommon to re-genotype sets of
    samples to use as positive controls in future studies or for diagnostic 
    panels. To save cost, it's often desireable to have the minimum number of
    samples that represent all of the alleles in the data. This package provides
    a procedure that will select these samples with alternative options. The 
    name 'repvar' stands for 'REPresent VARiables'.
License: MIT + file LICENSE
Encoding: UTF-8
LazyData: true
Roxygen: list(markdown = TRUE)
RoxygenNote: 6.0.1
Suggests: 
    testthat,
    covr,
    tibble,
    tidyr,
    dplyr,
    purrr,
    knitr,
    rmarkdown
VignetteBuilder: knitr
```

-   URL for the package (the development repository, not a stylized html page):

https://github.com/zkamvar/repvar/

-   Who is the target audience and what are scientific applications of this package?  

Population geneticists who use the adegenet package.

-   Are there other R packages that accomplish the same thing? If so, how does
yours differ or meet [our criteria for best-in-category](https://github.com/ropensci/onboarding/blob/master/policies.md#overlap)?

Not that I know of.

CC: @sporangia

**Comment by noamross** [comment]
Thank you for your submission, @zkamvar!  Can you comment on how your package fits into our Aims and Scope? (https://ropensci.github.io/dev_guide/policies.html#aims-and-scope).  This is an edge case that might go either way - on one hand, I think this falls under a statistical method, which is outside our scope.  However, it's possible it might make sense under the reproducibility category.

**Comment by zkamvar** [comment]
Hi @noamross,

Yes, the question of Aims and Scope is a bit tricky for this one.

I believe this fits under reproducibility because the goal of this package is to provide researchers with a tool that aids in selecting positive controls for reproducibility in population genetic studies. Otherwise, this process of selecting representative samples for re-genotyping is normally performed by hand. Thus, while a bit niche, this tool provides a way of tracking the provenance for the choice of the positive controls.

**Comment by noamross** [comment]
Sorry for the delay on this.  The editorial board discussed this and decided that, while this is an edge case, if submitted we'd consider it in scope.  We would likely aim to have at least one reviewer from a non-genetic field to consider other applications and associated documentation - you may want to consider if there are other relevant examples to include.

**Comment by noamross** [comment]
I'll go ahead and close this issue. To submit, please open another one with the full template.  Thanks!

**Comment by zkamvar** [comment]
Huzzah! Thank you! I'll talk with my collaborator and submit something soon :)
