### ISSUE TITLE
Pre-submission inquiry: frite

### ISSUE THREAD

**Issue by visuelledata** [ropensci/onboarding#235]
### Summary

-   What does this package do? (explain in 50 words or less):
This package provides basic tools for code generation and diagnostic functions for testing other functions. 

-   Paste the full DESCRIPTION file inside a code block below:

```
Type: Package
Package: frite
Title: Functions Writing Functions
Version: 0.1.0.9000
Author: Christopher Peralta [aut, cre]
Maintainer: Christopher Peralta <chris99994@gmail.com>
Description: Tools for writing and modifying functions with code. It contains functions 
    for adding, removing, and editing code in functions. Additionally, it contains 
    diagnostic functions to test your code. 
License: MIT + file LICENSE
Encoding: UTF-8
LazyData: true
Imports:
    assertthat (>= 0.2.0),
    magrittr (>= 1.5.0),
    purrr (>= 0.2.4), 
    tictoc (>= 1.0.0), 
    stringr (>= 1.3.0)
Depends:
    R (>= 3.5.0)
Suggests:
    knitr,
    rmarkdown,
    testthat
VignetteBuilder: knitr
URL: https://github.com/visuelledata/frite
BugReports: https://github.com/visuelledata/frite/issues
RoxygenNote: 6.0.1
```

-   URL for the package (the development repository, not a stylized html page):
https://github.com/visuelledata/frite

- Please indicate which category or categories from our [package fit policies](https://github.com/ropensci/onboarding/blob/master/policies.md#package-fit) this package falls under ***and why**?

General workflow as this package consists of functions that will assist users in writing their code. 

-   Who is the target audience and what are scientific applications of this package?  
The target audience consists of two groups. The first audience is anyone who wishes to take steps into code generation in R. The second are people who can make use of the diagnostic functions to check their code. 

-   Are there other R packages that accomplish the same thing? If so, how does
yours differ or meet [our criteria for best-in-category](https://github.com/ropensci/onboarding/blob/master/policies.md#overlap)?
There are none that I know of or was able to find. 

### Requirements

Confirm each of the following by checking the box.  This package:

- [x] does not violate the Terms of Service of any service it interacts with. 
- [x] has a CRAN and OSI accepted license.
- [x] contains a README with instructions for installing the development version. 
- [x] includes documentation with examples for all functions.
- [x] contains a vignette with examples of its essential functions and uses.
- [x] has a test suite.
- [x] has continuous integration, including reporting of test coverage, using services such as Travis CI, Coveralls and/or CodeCov.
- [x] I agree to abide by [ROpenSci's Code of Conduct](https://github.com/ropensci/onboarding/blob/master/policies.md#code-of-conduct) during the review process and in maintaining my package should it be accepted.

### Detail

- [x] Does `R CMD check` (or `devtools::check()`) succeed?  Paste and describe any errors or warnings:
There are no errors, warnings, or notes.

- [x] Does the package conform to [rOpenSci packaging guidelines](https://github.com/ropensci/onboarding/blob/master/packaging_guide.md)? Please describe any exceptions:

- If this is a resubmission following rejection, please explain the change in circumstances:
It is not. 

- If possible, please provide recommendations of reviewers - those with experience with similar packages and/or likely users of your package - and their GitHub user names:

**Comment by maelle** [comment]
Hi @visuelledata, thanks for your submission. Unfortunately, this package doesn't fit in one of our categories: "General workflow" is actually a category of packages we're unlikely to accept (see [the aims and scope section](https://ropensci.github.io/dev_guide/policies.html#aims-and-scope)). Thanks again for your submission, and good luck with `frite` development and promotion!
