### ISSUE TITLE
prozor

### ISSUE THREAD

**Issue by wolski** [ropensci/onboarding#240]
### Summary

-   What does this package do? (explain in 50 words or less):

This package is used at our core facility to generate FASTA sequence databases from smaller fasta files. It also is used to compute false discovery rates for mass spectrometric search results on PSM, peptide and protein level. It also is used for teaching. Using this package protein inference in bottom-up proteomics can be performed.

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: prozor
Type: Package
Title: Minimal Protein Set Explaining Peptide Spectrum Matches
Version: 0.2.10
Author: Witold Wolski
Maintainer: Witold Wolski <wewolski@gmail.com>
Description: Determine minimal protein set explaining
    peptide spectrum matches. Utility functions for creating fasta amino acid databases with decoys and contaminants.
    Peptide false discovery rate estimation for search results on psm, precursor, peptide and protein
    level.
License: GPL-3
LazyData: TRUE
Imports:
    AhoCorasickTrie,
    Matrix,
    doParallel,
    foreach,
    plyr,
    readr,
    seqinr,
    stringr,
    dplyr
URL: https://github.com/protviz/prozor
BugReports: https://github.com/protviz/prozor/issues
Repository: CRAN
RoxygenNote: 6.0.1
Suggests: knitr,
    rmarkdown
VignetteBuilder: knitr
```

-   URL for the package (the development repository, not a stylized html page):

https://github.com/protViz/prozor

- Please indicate which category or categories from our [package fit policies](https://github.com/ropensci/onboarding/blob/master/policies.md#package-fit) this package falls under ***and why**(? (e.g., data retrieval, reproducibility. If you are unsure, we suggest you make a pre-submission inquiry.):

data munging, reproducibility

-   Who is the target audience and what are scientific applications of this package?  

mass spectrometry proteomics

-   Are there other R packages that accomplish the same thing? If so, how does
yours differ or meet [our criteria for best-in-category](https://github.com/ropensci/onboarding/blob/master/policies.md#overlap)?

-   If you made a pre-submission enquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.

### Requirements

Confirm each of the following by checking the box.  This package:

- [x] does not violate the Terms of Service of any service it interacts with. 
- [x] has a CRAN and OSI accepted license.
- [x] contains a README with instructions for installing the development version. 
- [x] includes documentation with examples for all functions.
- [x] contains a vignette with examples of its essential functions and uses.
- [ ] has a test suite.
- [x] has continuous integration, including reporting of test coverage, using services such as Travis CI, Coveralls and/or CodeCov.
- [x] I agree to abide by [ROpenSci's Code of Conduct](https://github.com/ropensci/onboarding/blob/master/policies.md#code-of-conduct) during the review process and in maintaining my package should it be accepted.

#### Publication options

- [x] Do you intend for this package to go on CRAN?  
- [ ] Do you wish to automatically submit to the [Journal of Open Source Software](http://joss.theoj.org/)? If so:
    - [ ] The package has an **obvious research application** according to [JOSS's definition](http://joss.theoj.org/about#submission_requirements).
    - [ ] The package contains a `paper.md` matching [JOSS's requirements](http://joss.theoj.org/about#paper_structure) with a high-level description in the package root or in `inst/`.
    - [ ] The package is deposited in a long-term repository with the DOI: 
    - (*Do not submit your package separately to JOSS*)
- [ ] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:
    - [ ] The package is novel and will be of interest to the broad readership of the journal. 
    - [ ] The manuscript describing the package is no longer than 3000 words.
    - [ ] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal (see [MEE's Policy on Publishing Code](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/journal-resources/policy-on-publishing-code.html))
    - (*Scope: Do consider MEE's [Aims and Scope](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/aims-and-scope/read-full-aims-and-scope.html) for your manuscript. We make no gaurantee that your manuscript willl be within MEE scope.*)
    - (*Although not required, we strongly recommend having a full manuscript prepared when you submit here.*)
    - (*Please do not submit your package separately to Methods in Ecology and Evolution*)

### Detail

- [x] Does `R CMD check` (or `devtools::check()`) succeed?  Paste and describe any errors or warnings:

- [ ] Does the package conform to [rOpenSci packaging guidelines](https://github.com/ropensci/onboarding/blob/master/packaging_guide.md)? Please describe any exceptions:
  function naming is CamelCase at the moment but happy to change this.

- If this is a resubmission following rejection, please explain the change in circumstances:

- If possible, please provide recommendations of reviewers - those with experience with similar packages and/or likely users of your package - and their GitHub user names:

**Comment by maelle** [comment]
Thanks for your submission @wolski, we're discussing scope.

Regarding data munging could you answer the "Are there other R packages that accomplish the same thing? If so, how does yours differ or meet our criteria for best-in-category?" question in the template. I see packages reading FASTA files including one of Bioconductor.

Could you also clarify the reproducibility part as well? Including potential overlap with other packages if relevant.

Thanks.

**Comment by maelle** [comment]
:wave: @wolski could you please answer the questions above?

**Comment by maelle** [comment]
Closing this since there was no response in 2 months.
