### ISSUE TITLE
Pre-submisstion Inquiry: colocr

### ISSUE THREAD

**Issue by MahShaaban** [ropensci/onboarding#241]
I developed this simple package `colocr` for conducting the co-localization analysis of microscopy images. The package comes with a shinyapp to interactively choose the regions of interest.  And it calculates two simple statistics to quantify the co-localization of two proteins in a certain cell. 

I wonder whether this would be of interest to rOpenSci.

The GitHub repo is [https://github.com/MahShaaban/colocr](https://github.com/MahShaaban/colocr)

Thanks

**Comment by maelle** [comment]
Thanks for your pre-submission inquiry @mahshaaban! Can you confirm that the primary goal of the package is to compute **statistics** from images? Methods packages are out of scope.

For reference https://ropensci.github.io/dev_guide/policies.html#aims-and-scope

**Comment by MahShaaban** [comment]
Thanks, @maelle. I am aware of the fact that methods packages are out of the scope. Although the main use of the package is to compute co-localization stats, this is not a significant part of what the package does. It's just a one call to `cor()`. What the package focuses on automating the selection of regions of interest in the images. In addition, the package contains a shiny app to interactively perform the same task.

**Comment by maelle** [comment]
Sorry to ask so many questions, but how do people usually get these statistics, would you argue that with this package they'd be more prone to using a script rather than a click-and-point software?

**Comment by MahShaaban** [comment]
That's alright. 
I'd say yes. There are two cases where using scripts is more convenient. These are 

1. Analyzing a large number of images
2. Maintaining a reproducible workflow

In my research, I care a lot about reproducibility. While I mainly use high throughput data, often the case my work is followed by wet lab experiments for validation. Analyzing 10s of pictures may be doable in programs like **ImageJ** but would make it difficult to use the raw images in the study workflow. This was the reason I started this simple package.

**Comment by maelle** [comment]
Thanks @MahShaaban!

After discussion we agree that your package is in scope so please submit it when it's ready!

A note about two rOpenSci's packages that **might** be useful
* [`magick`](https://github.com/ropensci/magick)
* [`ijtiff`](https://github.com/ropensci/ijtiff)

**Comment by MahShaaban** [comment]
Thanks a lot, @maelle. Will do.
