### ISSUE TITLE
Pre-submission inquiry: panelr

### ISSUE THREAD

**Issue by jacob-long** [ropensci/onboarding#245]
I'm creating this issue to get a sense of whether this package could be in scope. 

I originally started working on this because I wanted to automate the specification of certain regression models for panel (i.e., repeated measures) survey data, but I've come to realize the most widely beneficial thing I've developed may be the "infrastructure" that I created along the way.

The aspect that would be of potential interest/relevance to rOpenSci would be the `panel_data` object class that acts as a data frame for panel surveys or time series cross section data. This is built on the (grouped) `tibble` and has some safeguards in place to avoid common ways a user might accidentally make analytic errors when creating variables, data cleaning, and so on. I also have `widen_panel` and `long_panel`, which are domain-specific refinements of `reshape` that aim to help take the data in the format it is often received by the researcher and get it into the appropriate format for analysis. There are a few more things in this vein that are there or in the works, but I'll keep it brief for now. Generally speaking, an aim of the package is to reduce the amount of programming and the necessary level of programming skill to manage this type of data in R.

My sense is the closest fit in the scope is the **data munging** category, but obviously if I thought it was a clear fit I wouldn't be asking :)

It seems to me that to fit with rOpenSci, I would need to spin off the modeling functions into a separate package. Assuming I'm right about that, I'd ask that you consider whether the package *sans modeling functions* is in scope.

Link: https://github.com/jacob-long/panelr

Thanks!

**Comment by maelle** [comment]
Thanks for your inquiry @jacob-long! We've discussed your pre-submission and come to the conclusion that the data munging your package provides is too general for our suite. Thanks again!
