### ISSUE TITLE
ipc: Tools for message passing between processes

### ISSUE THREAD

**Issue by ifellows** [ropensci/onboarding#249]
### Summary

-   What does this package do? (explain in 50 words or less):

This package provides tools for passing messages between R processes. 
    Shiny examples are provided showing how to perform useful tasks such as: 
    updating reactive values from within a future, progress bars for long running 
    async tasks, and interrupting async tasks based on user input.

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: ipc
Type: Package
Title: Tools for message passing between processes
Version: 0.1.0
Author: Ian Fellows
Maintainer: Ian Fellows <ian@fellstat.com>
Description: This package provides tools for passing messages between R processes. 
    Shiny Examples are provided showing how to perform useful tasks such as: 
    updating reactive values from within a future, progress bars for long running 
    async tasks, and interrupting async tasks based on user input.
Imports: R6, shiny, txtq, redux
License: GPL-2
Encoding: UTF-8
LazyData: true
Suggests: testthat,
    knitr,
    rmarkdown,
    future,
    promises
VignetteBuilder: knitr
RoxygenNote: 6.1.0

```

-   URL for the package (the development repository, not a stylized html page):

https://github.com/fellstat/ipc

- Please indicate which category or categories from our [package fit policies](https://github.com/ropensci/onboarding/blob/master/policies.md#package-fit) this package falls under ***and why**(? (e.g., data retrieval, reproducibility. If you are unsure, we suggest you make a pre-submission inquiry.):

data munging : because the package takes data from one process and processes it in another

-   Who is the target audience and what are scientific applications of this package?  

This package can be applied to high performance computing environments, easily allowing parallel worker processes to communicate partial results or progress to the main thread. Another major use case is to support asynchronous web based user interfaces to long running statistical algorithms.

-   Are there other R packages that accomplish the same thing? If so, how does
yours differ or meet [our criteria for best-in-category](https://github.com/ropensci/onboarding/blob/master/policies.md#overlap)?

Several packages have been written to handle the passing of text or binary data between processes (e.g. [@txtq], [@liteq], and [@rzmq]). What is lacking is a framework to easily pass R objects between processes along with an associated signal, and have handler functions automatically execute them in the receiving process. Additionally, it is desirable to have a system that can be backed flexibly either through the file system or a database connection The `ipc` R package aims to fill this void.

-   If you made a pre-submission enquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.

none

### Requirements

Confirm each of the following by checking the box.  This package:

- [ x] does not violate the Terms of Service of any service it interacts with. 
- [ x] has a CRAN and OSI accepted license.
- [ x] contains a README with instructions for installing the development version. 
- [ x] includes documentation with examples for all functions.
- [ x] contains a vignette with examples of its essential functions and uses.
- [ x] has a test suite.
- [ x] has continuous integration, including reporting of test coverage, using services such as Travis CI, Coveralls and/or CodeCov.
- [ x] I agree to abide by [ROpenSci's Code of Conduct](https://github.com/ropensci/onboarding/blob/master/policies.md#code-of-conduct) during the review process and in maintaining my package should it be accepted.

#### Publication options

- [ x] Do you intend for this package to go on CRAN?  
- [ x] Do you wish to automatically submit to the [Journal of Open Source Software](http://joss.theoj.org/)? If so:
    - [ x] The package has an **obvious research application** according to [JOSS's definition](http://joss.theoj.org/about#submission_requirements).
    - [ x] The package contains a `paper.md` matching [JOSS's requirements](http://joss.theoj.org/about#paper_structure) with a high-level description in the package root or in `inst/`.
    - [ ] The package is deposited in a long-term repository with the DOI: 
    - (*Do not submit your package separately to JOSS*)
- [ ] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:
    - [ ] The package is novel and will be of interest to the broad readership of the journal. 
    - [ ] The manuscript describing the package is no longer than 3000 words.
    - [ ] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal (see [MEE's Policy on Publishing Code](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/journal-resources/policy-on-publishing-code.html))
    - (*Scope: Do consider MEE's [Aims and Scope](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/aims-and-scope/read-full-aims-and-scope.html) for your manuscript. We make no gaurantee that your manuscript willl be within MEE scope.*)
    - (*Although not required, we strongly recommend having a full manuscript prepared when you submit here.*)
    - (*Please do not submit your package separately to Methods in Ecology and Evolution*)

### Detail

- [ x] Does `R CMD check` (or `devtools::check()`) succeed?  Paste and describe any errors or warnings:

- [ x] Does the package conform to [rOpenSci packaging guidelines](https://github.com/ropensci/onboarding/blob/master/packaging_guide.md)? Please describe any exceptions:

The package uses camel case so as to be consistent with shiny, which is a major use case.

- If this is a resubmission following rejection, please explain the change in circumstances:

- If possible, please provide recommendations of reviewers - those with experience with similar packages and/or likely users of your package - and their GitHub user names:

@wch
@jcheng5

**Comment by maelle** [comment]
Thanks for your submission @ifellows! This seems to be a very useful package, however, such a messaging package is out-of-scope for onboarding since it's a general computing package cf https://ropensci.github.io/dev_guide/policies.html#aims-and-scope 

Note that `rzmq` was developed by staff, hence its being under the ropensci organization despite its being out-of-scope for onboarding.

**Comment by maelle** [comment]
Feedback like this is worth a lot, many thanks! I think my wording of de

Actions taken: 

* We're actually thinking about changing the name of onboarding cf https://github.com/ropensci/onboarding-meta/issues/11 (and more recent discussions, in private though). It should make the distinction clearer, the same rules apply to all packages in the sense that packages developed by staff are only peer-reviewed via the onboarding system if they fall under the onboarding categories.

* we'll clarify some aspects in the guide, in particular [the role of the peer-reviewed badge](https://github.com/ropensci/dev_guide/issues/81) and the [evolution of scope over time](https://github.com/ropensci/dev_guide/issues/80) (at the time `iheatmapr` was onboarded we had a visualization category that we no longer feel able to cater for)

* I'll add a repo topic to all repos of packages that have been peer-reviewed https://github.com/ropensci/onboarding-meta/issues/60 since repos can't be filtered by badge.

Thanks again, and keep up the good R work too! 😺
