### ISSUE TITLE
Presubmission Inquiry - compareBars

### ISSUE THREAD

**Issue by daranzolin** [ropensci/onboarding#250]
This is a presubmission inquiry for [`compareBars`, an htmlwidget built on d3.js.](https://github.com/daranzolin/compareBars) While the package admittedly has a pretty narrow scope (comparing two levels across an ordinal variable), I find these visualizations more compelling than any of the options available with `ggplot(data, aes(x,y) + geom_bar(...)`. 

I myself am no d3 expert, so the package would certainly benefit from a more adept reviewer.

**Comment by maelle** [comment]
:wave: @daranzolin, thanks for your pre-submission, nice work! However, we no longer have a visualization category for onboarding see https://ropensci.github.io/dev_guide/policies.html#aims-and-scope so this package would be out of scope. Thanks again for your asking! I hope you can receive d3 feedback in other venues (feel free to post to our discuss forum :wink:)
