### ISSUE TITLE
Pre-submission queries: `rakeR`

### ISSUE THREAD

**Issue by philmikejones** [ropensci/onboarding#251]
I'm considering submitting my package, `rakeR``, to the ropensci suite but have a few queries before I do. 

## Purpose
`rakeR` is a tool for _spatial microsimulation_, useful to geographers, other social scientists, and potentially others. In the UK at least, getting survey data with geographical identifiers is difficult. For example, the UK data archive operate three levels of data security and to obtain useful geographical information requires the most secure level of access. Spatial microsimulation simulates this geographical information using more open data more readily accessible to the researcher. In some cases, geographical data doesn't even exist to the simulation is the only way to estimate it.

## Queries
- Package fit: is such a tool a good fit with the aims of ropensci? It is a geospatial package, and could loosely be interpreted as one for accessing geospatial data
- Title: I would like to keep the capitalisation (rakeR) to distinguish it from the noun (raker). Is this a problem?
- Package overlap: there are other tools for spatial microsimulation available through CRAN/R so is rakeR sufficiently different? The other packages tend to be an implementation of an algorithm ([ipfp](https://github.com/awblocker/ipfp), [mipfp](https://github.com/jojo-/mipfp)), whereas the purpose of rakeR is to abstract the process/algorithm as much as possible to simplify the process for the user. The only similar tool I am aware of is [sms](https://cran.r-project.org/package=sms) but this has not been updated since 2015 and is not openly developed (the source code is available but is not held on Github or similar) and (admittedly in my own opinion) is easier to use.
- rakeR is already on CRAN, as it was released before I really knew what ropensci was!

## Editor/reviewer suggestions
- I'm based at the University of Sheffield and know @annakrystalli so it might be easiest for her to act as editor?
- @Robinlovelace is an expert on spatial microsimulation, and in fact much of the code in this package is based on his earlier scripts.

**Comment by maelle** [comment]
:wave: @philmikejones! Thanks for your pre-submission inquiry and apologies for the delay in answering, we were discussing. Unfortunately we think that this package, albeit very useful, isn't in scope because it's first and foremost the implementation of a statistical algorithm, which we don't have the capacities to review. Although it uses spatial data, it hasn't enough spatial aspects for us to consider it a geospatial package (e.g. no topology, projection, or spatial relationships in these data) and therefore we aren't able to review from that point of view either. We hope you find another venue for your package, thanks again for considering rOpenSci onboarding!

**Comment by Robinlovelace** [comment]
Just reading this now and understand the reasoning @maelle, thanks for feedback. Any other suggestions for a venue? @philmikejones I'd be happy to informally review the pkg, perhaps with help from the new https://github.com/ropenscilabs/pkgreviewr pkg. Regarding venue: not sure. But you could do a write-up for a journal like JASSS or even JSS if you think there's enough in there. Interested in the idea of abstracting the low-level bits for user friendliness. Should allow it to wrap other approaches like the under-development **neworder** C++ codebase-waiting-to-become-an-R-package: https://github.com/virgesmith/neworder

**Comment by philmikejones** [comment]
Thanks @maelle , appreciate you looking into it, and I think your response if fair.

@Robinlovelace it'd be great if you could take a look at the package. I'll open an issue in rakeR.
