### ISSUE TITLE
submission: carbonate

### ISSUE THREAD

**Issue by yonicd** [ropensci/onboarding#252]
### Summary

-   What does this package do? (explain in 50 words or less):

Create 'carbon.js' image outputs directly from the 'R' console. Use the outputs to apply the elegant code images in posters, slides, websites or on social media via twitter. 

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: carbonate
Title: Interact with 'carbon.js' directly from R
Version: 0.0.1
Authors@R: person(given  = "Jonathan",
                 family  = "Sidi",
                 email   = "yonicd@gmail.com",
                 role    = c("aut", "cre"),
                 comment = c(ORCID = "0000-0002-4222-1819"))
Description: Create 'carbon.js' image outputs directly from the 'R' console.
Depends: R (>= 3.2.0)
License: MIT + file LICENSE
Encoding: UTF-8
LazyData: true
RoxygenNote: 6.1.0
Imports: R6, clipr, magick, wdman, RSelenium, utils, httr, rtweet, yaml
Suggests: testthat, covr, knitr, rmarkdown
URL: https://github.com/yonicd/carbonate
BugReports: https://github.com/yonicd/carbonate/issues
Roxygen: list(markdown = TRUE)
HexURL: https://github.com/yonicd/carbonate/raw/master/tools/temp/hex.gif
VignetteBuilder: knitr

```

-   URL for the package (the development repository, not a stylized html page):

https://github.com/yonicd/carbonate

- Please indicate which category or categories from our [package fit policies](https://github.com/ropensci/onboarding/blob/master/policies.md#package-fit) this package falls under ***and why**(? (e.g., data retrieval, reproducibility. If you are unsure, we suggest you make a pre-submission inquiry.):

[e.g., "data extraction, because the package parses a scientific data file format"]

reproducibility, because it promotes sharing code in a reproducible fashion.

-   Who is the target audience and what are scientific applications of this package?  
academia, professional, developers, students

-   Are there other R packages that accomplish the same thing? If so, how does
yours differ or meet [our criteria for best-in-category](https://github.com/ropensci/onboarding/blob/master/policies.md#overlap)?

[gistfo](https://github.com/MilesMcBain/gistfo) does something similar, but there is no direct interaction with the carbon.now.sh site rather via a gist.

-   If you made a pre-submission enquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.

### Requirements

Confirm each of the following by checking the box.  This package:

- [x] does not violate the Terms of Service of any service it interacts with. 
- [x] has a CRAN and OSI accepted license.
- [x] contains a README with instructions for installing the development version. 
- [x] includes documentation with examples for all functions.
- [x] contains a vignette with examples of its essential functions and uses.
- [x] has a test suite.
- [x] has continuous integration, including reporting of test coverage, using services such as Travis CI, Coveralls and/or CodeCov.
- [x] I agree to abide by [ROpenSci's Code of Conduct](https://github.com/ropensci/onboarding/blob/master/policies.md#code-of-conduct) during the review process and in maintaining my package should it be accepted.

#### Publication options

- [x] Do you intend for this package to go on CRAN?  
- [ ] Do you wish to automatically submit to the [Journal of Open Source Software](http://joss.theoj.org/)? If so:
    - [ ] The package has an **obvious research application** according to [JOSS's definition](http://joss.theoj.org/about#submission_requirements).
    - [ ] The package contains a `paper.md` matching [JOSS's requirements](http://joss.theoj.org/about#paper_structure) with a high-level description in the package root or in `inst/`.
    - [ ] The package is deposited in a long-term repository with the DOI: 
    - (*Do not submit your package separately to JOSS*)
- [ ] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:
    - [ ] The package is novel and will be of interest to the broad readership of the journal. 
    - [ ] The manuscript describing the package is no longer than 3000 words.
    - [ ] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal (see [MEE's Policy on Publishing Code](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/journal-resources/policy-on-publishing-code.html))
    - (*Scope: Do consider MEE's [Aims and Scope](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/aims-and-scope/read-full-aims-and-scope.html) for your manuscript. We make no gaurantee that your manuscript willl be within MEE scope.*)
    - (*Although not required, we strongly recommend having a full manuscript prepared when you submit here.*)
    - (*Please do not submit your package separately to Methods in Ecology and Evolution*)

### Detail

- [x] Does `R CMD check` (or `devtools::check()`) succeed?  Paste and describe any errors or warnings:

- [x] Does the package conform to [rOpenSci packaging guidelines](https://github.com/ropensci/onboarding/blob/master/packaging_guide.md)? Please describe any exceptions:

- If this is a resubmission following rejection, please explain the change in circumstances:

- If possible, please provide recommendations of reviewers - those with experience with similar packages and/or likely users of your package - and their GitHub user names:

Lucy D’Agostino McGowan @LucyMcGowan : most likely user
Miles McBain @milesmcbain : familiar with carbon.now.sh api
Jim Hester @jimhester : familiar with R6

**Comment by maelle** [comment]
:wave: @yonicd! Thanks for your submission! Unfortunately, `carbonate` is out-of-scope for rOpenSci onboarding: although it does help with reproducibility (and is a very cool package!), it is a too general coding/communication tool that's beyond our current aims and scope. Thanks again for submitting `carbonate` to onboarding! We hope you find another venue for it.
