### ISSUE TITLE
Pre Submission Inquiry - DataSpaceR

### ISSUE THREAD

**Issue by juyeongkim** [ropensci/onboarding#260]
I was wondering if you would consider the `DataSpaceR` package for review. The package fits into the data retrieval category as it provides API access to the database.

https://github.com/CAVDDataSpace/DataSpaceR

`DataSpaceR` is an R interface to [the CAVD DataSpace](https://dataspace.cavd.org/cds/CAVD/app.view), a data sharing and discovery tool that facilitates exploration of HIV immunological data from pre-clinical and clinical HIV vaccine studies.

This package simplifies access to the database by taking advantage of the standardization of the database to hide all the [Rlabkey](https://cran.r-project.org/web/packages/Rlabkey/index.html) specific code away from the user, and it allows the users to access the study-specific datasets via an object-oriented paradigm.

**Comment by sckott** [comment]
We discussed and we think it is a good fit. Please do submit.

**Comment by juyeongkim** [comment]
thanks @sckott!
