### ISSUE TITLE
Rgoodreads - an R package for the Goodreads API

### ISSUE THREAD

**Issue by Famguy** [ropensci/onboarding#30]
* 1. What does this package do? (explain in 50 words or less)  

This R package acts as a wrapper for the read-only features of the Goodreads API. The
package has various features so as to search and retrieve information on books, authors,
users, reviews, etc. based on their ISBN, titles, ids, etc. in order to analyze them as R objects.

* 2. Paste the full DESCRIPTION file inside a code block below.  

```
Package: rgoodreads
Type: Package
Title: Client for the Goodreads API
Version: 0.1
Date: 2016-02-23
Author: Sagun Pai
Maintainer: <sagung.pai@gmail.com>
Description: This R package acts as a wrapper for the read-only features of the Goodreads API with the ability to retrieve information on books, authors, users, reviews, etc. so that they can be analyzed in R.
License: MIT
Depends:
    R (>= 3.1.1)
Imports:
    httr,
    XML,
    RCurl
LazyData: TRUE
URL: http://github.com/famguy/rgoodreads
BugReports: http://github.com/famguy/rgoodreads/issues
RoxygenNote: 5.0.1
```

* 3. URL for the package (the development repository, not a stylized html page)  

https://github.com/Famguy/rgoodreads

* 4. What data source(s) does it work with (if applicable)?  

It works on the Goodreads API. Check out the documentation [here](https://www.goodreads.com/api/documentation)

* 5. Who is the target audience?  

Book enthusiasts, people who want to use books data for their analysis

* 6. Are there other R packages that accomplish the same thing? If so, what is different about yours?  

None that I know of

* 7. Check the box next to each policy below, confirming that you agree. These are mandatory.  
    * [x] This package does not violate the Terms of Service of any service it interacts with.  
    * [ ] The repository has continuous integration with Travis CI and/or another service  
    * [ ] The package contains a vignette  
    * [x] The package contains a reasonably complete README with `devtools` install instructions  
    * [ ] The package contains unit tests  
    * [x] The package only exports functions to the NAMESPACE that are intended for end users  
* 8. Do you agree to follow the [rOpenSci packaging guidelines](https://github.com/ropensci/packaging_guide)? These aren't mandatory, but we strongly suggest you follow them. If you disagree with anything, please explain.  
    * [ ] Are there any package dependencies not on CRAN?  
    * [ ] Do you intend for this package to go on CRAN?  
    * [ ] Does the package have a CRAN accepted license?    
    * [ ] Did `devtools::check()` produce any errors or warnings? If so paste them below.  
* 9. Please add explanations below for any exceptions to the above:  
* 10. If this is a resubmission following rejection, please explain the change in circumstances.

**Comment by sckott** [comment]
@Famguy  did you mean to close this?
