### ISSUE TITLE
SwissHistMunData -- Data on mergers, splits, and other changes of Swiss municipalities since 1960

### ISSUE THREAD

**Issue by krlmlr** [ropensci/onboarding#31]
* Data on mergers, splits, and other changes of Swiss municipalities since 1960

```
Encoding: UTF-8
Package: SwissHistMunData
Title: Historicized Swiss Municipalities
Version: 0.0-1
Date: 2016-03-31
Authors@R: c(
    person("Kirill", "Müller", , "krlmlr+r@mailbox.org", c("aut", "cre")),
    person("Swiss Federal Statistical Office (SFSO), Swiss Statistics Web site", role = "cph")
    )
Description: Contains historicized municipality data for Switzerland from 1960
    onwards, from the "Historisiertes Gemeindeverzeichnis" of the Swiss
    Federal Statistical Office.
Depends: R (>= 2.10)
Imports: tibble
Suggests:
    testthat,
    logging
License: GPL-3
LazyData: true
RoxygenNote: 5.0.1
```

* https://github.com/krlmlr/SwissHistMunData
* Downloads data from a fixed URL as part of its testing procedure (which also checks that data is up to date)
* Data required for the [SwissCommunes](https://travis-ci.org/krlmlr/SwissCommunes) package, whose purpose is to compute mappings between municipality codes for arbitrary points in time.
* No other packages AFAIK.
* Check the box next to each policy below, confirming that you agree. These are mandatory.  
    * [x] This package does not violate the Terms of Service of any service it interacts with.  
    * [x] The repository has continuous integration with Travis CI and/or another service  
    * [ ] The package contains a vignette  
    * [ ] The package contains a reasonably complete README with `devtools` install instructions  
    * [ ] The package contains unit tests  
    * [x] The package only exports functions to the NAMESPACE that are intended for end users  
* Do you agree to follow the [rOpenSci packaging guidelines](https://github.com/ropensci/packaging_guide)? These aren't mandatory, but we strongly suggest you follow them. If you disagree with anything, please explain.  
    * [ ] Are there any package dependencies not on CRAN?  
    * [x] Do you intend for this package to go on CRAN?  
    * [x] Does the package have a CRAN accepted license?    
    * [ ] Did `devtools::check()` produce any errors or warnings? If so paste them below.  
* My first onboarding, I'd like to verify first that this package is a fit for rOpenSci.

**Comment by sckott** [comment]
Thanks for the submission!  Looking for reviewer

**Comment by sckott** [comment]
Reviewers: @sckott
Due: 2016-04-25

**Comment by sckott** [comment]
hey @krlmlr - Seems like this pkg and `SwissCommunes` fit together. Did you plan on submitting `SwissCommunes` here?  If not, we'll proceed, but if you did plan to, perhaps it makes more sense to submit together (either in this issue or a separate one). Thoughts?

**Comment by sckott** [comment]
@krlmlr any thoughts on the above comment?

**Comment by krlmlr** [comment]
Sorry, missed that. I'd be happy to host both packages here, but they'll need some polish first. I'll reopen.

**Comment by sckott** [comment]
Okay, thanks
