### ISSUE TITLE
onboarding ideas

### ISSUE THREAD

**Issue by sckott** [ropensci/onboarding#32]
* `lintr` - check that pkg has (available linters: https://github.com/jimhester/lintr#available-linters)
    * tests
    * vignette
    * etc....other built in checks
    * style checks for things like use `httr` instead of `RCurl`, unless good reason otherwise, etc. 
* is looking at travis logs good enough?  or should we make a prettier presentation somehow
* when travis checks done, post hook to ping back to issue or PR with a summary?  or somehow in the travis logs make it easy to find the important bits (e.g., things that don't pass)
* should we move to PR system, or stick with issue based system?
* there was some discussion of limiting review lengths, e.g,. a strategy could be to only look at internals of one function if there are many similar ones, etc. - Others have brought up limiting to a certain number of lines of code...
* others ...

cc/  @noamross

**Comment by noamross** [comment]
Not from the unconf, but something to elevate to updated guidance for authors, from the [review of **rnaturalearth**](https://github.com/ropensci/onboarding/issues/22#issuecomment-203498875):

>If you feel your reviewers have substantially contributed to the development of your package, we suggest you credit them in the DESCRIPTION file `Authors:` field as reviewers, like so:

    person("Lincoln", "Mullen", role = c("rev"))

**Comment by sckott** [comment]
Seems like a good idea - can you add to guide for authors

**Comment by noamross** [comment]
Done.  Also, new life goals for how I am listed in a future package:

```
> utils:::MARC_relator_db[utils:::MARC_relator_db$code %in% c('wde', 'wdc'),]
             term code                                                                                                description usage
260 Wood engraver  wde  A person or organization who makes prints by cutting the image in relief on the end-grain of a wood block      
261    Woodcutter  wdc A person or organization who makes prints by cutting the image in relief on the plank side of a wood block 
```

**Comment by noamross** [comment]
I think we want a formatted report rather than just logs, with things ordered from most important (editor-rejects) to 'useful to know' info for reviewers.

Other things to potentially run in the the check/put in the report:

-   Just the NOTES/WARNINGS/ERRORS from R CMD Check
-   exported functions use the same naming style
-   what CI service is being used? (A Linux AND Windows CI?)
-   README.Rmd is used if there is substantial code in README
-   Lines of code in .R files, Roxygen comments, and tests (I think measuring this and a little more experience might be useful before we move to limiting review size).
-   List of packages in `Depends`
-   Is there a code of conduct?
-   `print()` or `cat()` calls in functions

**Comment by noamross** [comment]
I think I'm going to start a discuss thread for reviewers to ask them what would be useful in an automated report.

**Comment by Robinlovelace** [comment]
Haha that's awesome - your code confirms that my guess of 'rev' was about right - not sure why R packages need wood engravers though - maybe to ensure their longevity after the internet goes down? ;)

```
utils:::MARC_relator_db[utils:::MARC_relator_db$code %in% c('rev', 'wdc'),]
          term code                                                                                                description
223   Reviewer  rev           A person or organization responsible for the review of a book, motion picture, performance, etc.
261 Woodcutter  wdc A person or organization who makes prints by cutting the image in relief on the plank side of a wood block
    usage
```

Many thanks @noamross for showing me what those codes mean - any more info where those codes come from appreciated.

**Comment by sckott** [comment]
> start a discuss thread  

okay

**Comment by noamross** [comment]
@Robinlovelace A little googling reveals that these are codes for MARC bibliographic standards, which are what Library of Congress uses for metadata: http://www.loc.gov/marc/ , https://www.loc.gov/marc/relators/relaterm.html

**Comment by Robinlovelace** [comment]
Thanks for the info - impressed R incoroporates those codes into `person()` - apologies for being slow, see now that's also linked to in `?person`.

**Comment by sckott** [comment]
discussion at https://discuss.ropensci.org/t/what-additional-automated-checks-would-be-useful-for-package-review/347
