### ISSUE TITLE
Consolidating onboarding documentation

### ISSUE THREAD

**Issue by noamross** [ropensci/onboarding#37]
Documentation related to onboarding is currently fragmented across:

-   README in this repository
-   Reviewers' guide in this repository's wiki, along with other various stubs in the wiki.
-   [README in the policies repo](https://github.com/ropensci/policies#ropensci-policies)
-   [README and NEWS sample in the packaging guide repo](https://github.com/ropensci/packaging_guide#ropensci-packaging-guide)

Fragmentation can lead to various parts being difficult to track, and parts getting out of sync. I propose consolidating this documentation all into this repository and eliminating the wiki.  This would include an expanded README with "Why submit?" and "Why review?" and then gets to "How", where we link to other files such as packaging guide, reviewers guide, policies, etc.

We may want an an even shorter version of the README this on the rOpenSci website, perhaps as a top-level page linked to from https://ropensci.org/packages/, or just second paragraph on that page?

**Comment by sckott** [comment]
Makes sense to me to consolidate here. and to add something to packages page
