### ISSUE TITLE
Start this from the command line?

### ISSUE THREAD

**Issue by karthik** [ropensci/onboarding#4]
@sckott @richfitz
Tell me if this idea is too complicated. Instead of a user coming over to the repo, then copying a block of text into a new issue and editing in place, how about we do this programmatically? We can write a really  lightweight package that wraps the CLI for GitHub issues. Then from the working directory of a package (or passing the path) to something akin to `devtools::release`, a user does `ropensci_contribute()` (or something like that).

The function will read the description, extract author information, license, Travis integration, coveralls integration, vignette info etc. The remaining questions will be a wizard, just like `devtools::release`. At the end, all the information is formatted and an issue is programmatically pushed to the repo. 

Perhaps too much (I am starting to think so) but just wanted to throw this ide out (perhaps for a later time).

**Comment by richfitz** [comment]
I think that's a great idea, and would not be too complicated to set up, so long as the OAuth headache is not too bad.  If it's possible to do it with a one-off password request or something that'd be ideal.  If people have to do that thing when you register an application they won't do it.

**Comment by karthik** [comment]
Yeah I agree. No password would be required. First time use will open browser and request permission to access issues.

**Comment by sckott** [comment]
@richfitz yeah, i think we'd just register an app, and they auth with ours. 

I imagine some may not want to deal with doing it from R, so would be good to allow both

don't know if there's anything in these useful wrt this if people will be doing this process from R:  

https://github.com/ropensci/ropkgs (reads from the registry below, and other stuff)
https://github.com/ropensci/roregistry (idea was to keep a machine readable json registry of ropensci pkgs)

**Comment by cboettig** [comment]
Great idea.  :+1: for having options to do either way

**Comment by sckott** [comment]
started the pkg `ro` here https://github.com/ropensci/ro - i imagine we'll stick with the browser based workflow for now though?

**Comment by karthik** [comment]
I think so. If only for the fact that the questions will evolve in the near future as we onboard the first few.

**Comment by karthik** [comment]
Closing for now, does not seem like a high priority item.
