### ISSUE TITLE
Clarification about where paper.md should be

### ISSUE THREAD

**Issue by daattali** [ropensci/onboarding#65]
One of the new checkboxes in the template is

```
The package contains a paper.md with a high-level description.
```

This doesn't say *where* that file should live.  Does it matter where? Is there a recommendation?  My personal vote would be to not have it in the package root since CRAN doesn't like that, and maybe have it under `inst/joss/paper.md`?  Regardless of where it is, it should be clarified

**Comment by sckott** [comment]
i don't know the JOSS rules, maybe @noamross 

> CRAN doesn't like that

yeah, but can't you just add the file to `.Rbuildignore`

**Comment by daattali** [comment]
You could, but I personally think it's better to put it in inst/ so that
it's included in the package and doesn't contaminate the main directory
when someone browses the pkg on github. It's definitely up to personal
taste though.

**Comment by sckott** [comment]
@noamross @karthik i'm not familiar with what JOSS wants, up to you

**Comment by noamross** [comment]
@arfon Can JOSS have `paper.md` anywhere but the top-level directory in the repo?

**Comment by arfon** [comment]
> @arfon Can JOSS have paper.md anywhere but the top-level directory in the repo?

@noamross - yep, it can be anywhere in the repo: https://github.com/openjournals/whedon/blob/3fa7c4626ec7ab243111a75fd2c0acad96f20a89/lib/whedon/processor.rb#L41-L49

**Comment by noamross** [comment]
Thanks, @arfon!  @daattali, you can put your paper in `inst/` or wherever you feel most appropriate, then.
