### ISSUE TITLE
packages on deck

### ISSUE THREAD

**Issue by sckott** [ropensci/onboarding#7]
so I don't lose track of these (pkgs of people interested in submitting here when we're ready):

`stplanr`, `FredR`, `driver`, `rsdmx`, `rusda`

**Comment by richfitz** [comment]
![herding-cats-o](https://cloud.githubusercontent.com/assets/1558093/6910241/6b52c676-d79c-11e4-9b4a-7413b70be9a0.gif)

**Comment by sckott** [comment]
inviting people to submit here now.... :bullettrain_front:

**Comment by sckott** [comment]
all invited to submit
