### ISSUE TITLE
Should we add this into guidelines?

### ISSUE THREAD

**Issue by karthik** [ropensci/onboarding#8]
https://twitter.com/JennyBryan/status/584243412682944512

or perhaps the style guide?

**Comment by richfitz** [comment]
styleguide, perhaps in a "tips and hints" section?

**Comment by gaborcsardi** [comment]
I am not actually sure how useful/important this is. Even if you designate `.R` files as language `R`, if you have a lot of C/C++ or HTML/JS, etc. code, then Github will categorize the repo as such. And the detection on the `.R` files could have been good in the first place, anyway.

But it surely does not hurt.

**Comment by karthik** [comment]
@gaborcsardi Agreed.
I really only see this useful is when someone has extensive html documentation in a gh-pages repo and the stats show heavy percentages of css and html. Agree with @richfitz that it should go under tips and tricks.
WRT to C/C++ and JS, those are all intentionally there and it makes sense for the language stats to take those files into account.

**Comment by gaborcsardi** [comment]
The (summarized) language stats consider all branches? In this case, yes, `gh-pages` can be misleading.

**Comment by richfitz** [comment]
I've seen .h files categorised as C when they're C++; it's not a big deal, but it's nice to know there's a fix.

**Comment by jennybc** [comment]
Just to qualify what @karthik said: "extensive" documentation can mean exactly one HTML file. In the twitter conversation that set me on that little journey, the other guys repo was 70% R by line but 85% HTML by character or bytes, which is apparently what GitHub actually consults.

And re: @gaborcsardi's point: true it doesn't really hurt anything for R package repos to be classified as another language. But in a community-minded way, advanced GitHub searching sure works better if the language stats are as morally correct as possible.

**Comment by karthik** [comment]
Closing here, will open in style guide.

**Comment by maelle** [comment]
Just seeing this from the packaging_guide repo that I'm going to archive.

For the record I actually added some lines about this to dev_guide https://ropensci.github.io/dev_guide/grooming.html#make-your-repository-more-discoverable
