### ISSUE TITLE
Add tip to use devtools::spell_check() in the guidelines

### ISSUE THREAD

**Issue by maelle** [ropensci/onboarding#85]
I have the impression that `devtools::spell_check()` is not very well-known yet, so would it make sense to add a sentence about it in the guidelines? One gets many false positives using it but also the typos (and I don't think `goodpractice` does that?).

**Comment by sckott** [comment]
@masalmon Good suggestion. I don't think `goodpractice` does spell checking AFAIK. 

Will add that.

**Comment by noamross** [comment]
We should add it to the set of checks we do so editors, too.

**Comment by noamross** [comment]
*as* editors

**Comment by noamross** [comment]
Not sure what the current state of automation work is, but I've been adding `goodpractice` checks to my `after_success` commands in Travis-CI with the command:

    `Rscript -e 'library(goodpractice);gp(checks=all_checks()[grepl("(rcmdcheck|covr)",all_checks())])'`

This skips things done in `R CMD check` and `covr` as they are run already, and gives me the `goodpractice()` output at the end of the Travis log.  I suppose I'll add `spell_check()` to the battery of tests!
