### ISSUE TITLE
sperrorest: Parallelized spatial error estimation and variable importance assessment for geospatial machine learning

### ISSUE THREAD

**Issue by pat-s** [ropensci/onboarding#89]
### Summary

-   What does this package do? (explain in 50 words or less):
The package provides parallelized spatial error estimation and variable importance assessment for geospatial machine learning. By providing a generic function interface, `sperrorest` can be used with any statistical - and machine learning approach. It enables performing spatial cross-validation for spatial models, which should be preferred over non-spatial cross-validation. 

-   Paste the full DESCRIPTION file inside a code block below:

```R
Package: sperrorest
Type: Package
Title: Perform Spatial Error Estimation and Variable Importance in Parallel
Version: 1.0.0.9000
Date: 2016-10-04
Authors@R: c(
      person("Alexander", "Brenning", , "alexander.brenning@uni-jena.de",
        c("aut", "cre")),
      person("Patrick", "Schratz", , "patrick.schratz@uni-jena.de",
        "aut"),
      person("Tobias", "Herrmann", , "herrmann.tobias89@gmail.com",
        "aut")  
      )
Maintainer: Patrick Schratz <patrick.schratz@uni-jena.de>
BugReports: https://github.com/pat-s/sperrorest/issues
Depends: 
    R (>= 2.10)
Suggests:
    ipred,
    nnet,
    RSAGA,
    knitr, 
    testthat
Imports:
    pbapply,
    foreach,
    doParallel,
    snow,
    ROCR,
    parallel,
    graphics, 
    stats,
    rpart
Description: This package implements spatial error estimation and
    permutation-based variable importance measures for predictive models using
    spatial cross-validation and spatial block bootstrap.
License: GPL-2
LazyData: true
LazyLoad: yes
ByteCompile: true
Collate:
    'sperrorest-package.R'
    'sperrorest.R'
    'sperrorest_misc.R'
    'sperrorest_resampling.R'
    'sperrorest_error.R'
    'sperrorest_data.R'
    'parsperrorest.R'
Maintainer: Patrick Schratz <patrick.schratz@uni-jena.de>
RoxygenNote: 5.0.1
VignetteBuilder: knitr
```

-   URL for the package (the development repository, not a stylized html page): https://github.com/pat-s/sperrorest

-   Who is the target audience?  
Scientists dealing with spatial statistical - or machine learning models. 

-   Are there other R packages that accomplish the same thing? If so, what is different about yours?  
The well-known `caret` package serves as an interface for many statistical models in R. However, there is no dedication towards spatial models. Also, the newest major version of `sperrorest` has an integrated parallelised function (`parsperrorest()`) which highly reduces computation time of cross-validation runs. 

### Requirements

Confirm each of the following by checking the box.  This package:

- [x] does not violate the Terms of Service of any service it interacts with. 
- [x] has a CRAN and OSI accepted license.
- [x] contains a README with instructions for installing the development version. 
- [x] includes documentation with examples for all functions.
- [ ] contains a vignette with examples of its essential functions and uses.
- [x] has a test suite.
- [x] has continuous integration with Travis CI and/or another service.

#### Publication options

- [x] Do you intend for this package to go on CRAN?  
- [ ] Do you wish to automatically submit to the [Journal of Open Source Software](http://joss.theoj.org/)? If so:
    - [ ] The package contains a [`paper.md`](http://joss.theoj.org/about#paper_structure) with a high-level description in the package root or in `inst/`.
    - [ ] The package is deposited in a long-term repository with the DOI: 
    - (*Do not submit your package separately to JOSS*)

### Detail

- [x] Does `R CMD check` (or `devtools::check()`) succeed?  Paste and describe any errors or warnings:

- [ ] Does the package conform to [rOpenSci packaging guidelines](https://github.com/ropensci/packaging_guide)? Please describe any exceptions:
  - Vignette in the making
  - Function naming: Initial CRAN version used dots in function names ->this style has been kept consistent for the new version. 
  - still a lot of `cat()` calls in functions

- If this is a resubmission following rejection, please explain the change in circumstances:

- If possible, please provide recommendations of reviewers - those with experience with similar packages and/or likely users of your package - and their GitHub user names:

**Comment by sckott** [comment]
Hi @pat-s 

Thanks for your submission!

This looks like a really useful package! Including via the citations I saw perusing Google Scholar for this package. 

Unfortunately, it falls out of the scope for rOpenSci - statistical methods aren't something we do. We do Geospatial packages, but not of the statistical variety. See the fit guidelines for more: https://github.com/ropensci/onboarding/blob/master/policies.md#package-fit

We encourage you to submit to http://joss.theoj.org/

**Comment by pat-s** [comment]
@sckott Thanks for the information! I was unsure if this package fits in the 'geospatial' part. Thanks for the link and keep up the good work!

**Comment by sckott** [comment]
and thanks for submitting!  We really do appreciate you considering submitting here.
