### ISSUE TITLE
packages repo

### ISSUE THREAD

**Issue by cboettig** [ropensci/onboarding#9]
- 1. What does this package do? (explain in 50 words or less)  

Provides a CRAN-like repository for serving our R packages. See https://github.com/cboettig/packages readme for details.

- 2. Paste the full DESCRIPTION file inside a code block (bounded by ``` on either end).

N/A

- 3. URL for the package (the development repository, not a stylized html page)

https://github.com/cboettig/packages

- 4. What data source(s) does it work with (if applicable)?

R packages from https://github.com/ropensci

- 5. Who is the target audience?

Anyone wanting to install our R packages.

- 6. Check the box next to each policy below, confirming that you agree. These are mandatory.

N/A

* [ ] The repository has continuous integration with Travis and/or another service
* [ ] The package contains a vignette
* [ ] The package contains a reasonably complete readme with devtools install instructions
* [ ] The package contains unit tests

N/A

- 7. Do you agree to follow the [rOpenSci packaging guidelines](https://github.com/ropensci/packaging_guide)? These aren't mandatory, but we strongly suggest you follow them. If you disagree with anything, please explain.

I agree.

* [x] Are there any packages that your package depends on that are not on CRAN?

N/A

* [ ] Do you intend for this package to go on CRAN?

N/A

* [ ] Does the package have a CRAN accepted license?

N/A

* [ ] Did `devtools::check()` produce any errors or warnings? If so paste them below.

N/A

- 8. Please add explanations below for any exceptions to the above:

N/A

- 9. If this is a resubmission following rejection, please explain the change in cirucmstances.

**Comment by Robinlovelace** [comment]
One of the things most urgently needed in CRAN (or its equivalent), as documented in this excellent [paper](http://www.stat.tugraz.at/AJS/ausg121/121Hornik.pdf), is the need to rate and review packages, so people have an idea of whether they are downloading garbage or not. This would be the main selling point for me. Great idea though, love the fact that it will just work with `install.packages`.

**Comment by karthik** [comment]
Assigned @mine-cetinkaya-rundel as editor.

**Comment by karthik** [comment]
@mine-cetinkaya-rundel PS: Reviewer guidelines are here (https://github.com/ropensci/onboarding/wiki/For-Reviewers) but feel free to ping over email with additional questions.

**Comment by cboettig** [comment]
Closing this for now until the repo can be updated with better scripts from @richfitz

**Comment by sckott** [comment]
@cboettig where are we at on this?  still waiting on some infusion of @richfitz -ness

**Comment by cboettig** [comment]
The draft implementation is in https://github.com/cboettig/drat, and is
currently deployed on http://carlboettiger.info/drat via GitHub.  There's
still a few issues I need to work out with @richfitz, a bit more work to be
done on the automated deploy / update via circle, and some general tidying
and documentation.

**Comment by sckott** [comment]
Cool, exciting. 

is http://www.carlboettiger.info/drat/ supposed to 404?

**Comment by cboettig** [comment]
yes.  (the repo still works, though clearly that would be a good place to
put up a documentation page.)

this'll move over to an ropensci host anyway -- that's another thing to
work out.  We might host on a private server instead of Github just to
process the download logs....

**Comment by sckott** [comment]
heh, something for the future

**Comment by cboettig** [comment]
added these to the issues list https://github.com/cboettig/drat/issues/1

**Comment by cboettig** [comment]
I think we're ready to reopen this, as I think most of the pieces are now in place and we should migrate this to the ropensci accounts sooner than later (which might still be a bit of a pain updating all paths, but I can keep my branch open if necessary). 

I've updated the issues on https://github.com/cboettig/drat/issues/1

Still needs some further documentation (e.g. an nice index.html page), the download stats need to be tabulated, and we have to pick a name / url for the S3 bucket (e.g. packages.ropensci.org or drat.ropensci.org or whatever)

**Comment by sckott** [comment]
@cboettig since this is in ropensci now, should we close this? or do you still want to do a review

**Comment by cboettig** [comment]
We can close

On Mon, Oct 5, 2015, 10:52 PM Scott Chamberlain <notifications@github.com>
wrote:

> @cboettig <https://github.com/cboettig> since this is in ropensci now,
> should we close this? or do you still want to do a review
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ropensci/onboarding/issues/9#issuecomment-145748618>.
>
-- 

http://carlboettiger.info
