### ISSUE TITLE
Switch to recommending xml2 for XML authoring

### ISSUE THREAD

**Issue by jennybc** [ropensci/onboarding#97]
There's been a lot of positive change since the XML advice was written. Personally I would recommend authoring XML with xml2 w/o zero hesitation now.

https://github.com/ropensci/onboarding/blame/85a56b769aac151caa9053012c602b65f9d46ab1/packaging_guide.md#L155

**Comment by noamross** [comment]
This is in #91, my omnibus review process changes PR :)

**Comment by jennybc** [comment]
Awesome! Do you want to hold all those improvements off for one giant satisfying merge? Or might you cherry pick some things to master in the mean time?

**Comment by noamross** [comment]
Planning on a mass merge relatively soon with an accompanying blog post describing updates in the past year.
